### ISSUE TITLE
Destroying Naxxramas with an artifact inside didn't teleport the item outside and caused an exception

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#1000]
![image](https://user-images.githubusercontent.com/93258020/211373245-af970d2d-5bdf-470c-a323-cc428a7ab95a.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/c1f76a4fd47f9f7c5253ccccc37d5cd91fb1b29e
