### ISSUE TITLE
Review new Quel'thalas content

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1012]
1 unit - arcane annihilator
1 unit - Warlock
1 unit- Sunfury Warrior
1 upgrade - Sunfury Training
1 quest - Forgotten Knowledge
1 quest - Azshara's Archive

**Comment by YakaryBovine** [comment]
Follow-up tickets:
https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1016
https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1017
