### ISSUE TITLE
Warlock's Firestorm ability says that it calls down a storm of fire, but it actually calls down lightning

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1017]
Unfortunately I don't think this bug is fixable in the object editor, so I think we'll either need to replace the ability with something else or create a scripted version of Monsoon that can actually have its effect changed.

**Comment by TracyTheBoy** [comment]
Couldn't we just call it Lightning Storm?

**Comment by YakaryBovine** [comment]
Yep good point, that's another valid option.
