### ISSUE TITLE
Do something about the "Ruins of Stonemaul" Dragonmaw quest

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1019]
Currently Stonemaul starts hostile because of the Ruins of Stonemaul quest being registered to Dragonmaw.

**Comment by TracyTheBoy** [comment]
Since Stonemaul is now supposed to be a Frostwolf base again, the dragonmaw quest should not be registered anymore or deleted entirely.
