### ISSUE TITLE
Legion tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1062]
- [x] Legion Herald mentions they have Shadow Infusion, but they don't
- [x] Nether Pit doesn't mention War Plating
- [x] Fel Guard says they have Heavy Plating, but they have War Plating
- [x] Fel Guard says they have Heavy Plating (War Plating)
- [x] Fel Guard says they have Cleaving Attack, but they don't
- [x] Anetheron's Feedback ability requires researching "Improved Carrion Swarm"
- [x] Anetheron's Summon Hounds says it summons Fel Hounds, but it summons Fel Stalkers
- [x] Sky Barge shares an icon with Healing Spray
- [x] Dreadlord says it has Sargeras Sight, but it has Sight of Sargeras
- [x] Mal'ganis' and Tichondrius' tooltip says he has Astral Walk, but he actually must learn it first
- [x] Anetheron's tooltip doesn't mention Permanent Invisibility
- [x] The Argus Incursion quest does not indicate what the reward is
- [x] Fear Aura buff name should be red, since it is negative
- [x] Fear Aura buff tooltip doesn't describe what it does
- [x] Rain of Chaos level 1 indicates that it summons "basic Infernals", but it summons Abyssals
- [x] Rain of Chaos level 1 indicates that it summons "powerful Infernals", but it summons Doomfire Abyssals
- [x] Rain of Chaos level 1 indicates that it summons "elite Infernals", but it summons Gargantuan Abyssals (which have a really ugly tint)
- [x] Infernal Juggernaut's Inferno says it lasts 2 seconds
- [x] Flying Horrors research mentions Infernal Machine Factory, which doesn't exist
- [x] Infernal Foothold quest mentions Infernal Machine Factory, which doesn't exist
- [x] Argus Incursion flavour and description texts are the wrong way around

**Comment by SebastianTanoni** [comment]
I dont know how to fix the buff color, so im unassigning myself from this

**Comment by HerrDave** [comment]
No worries, I got this :)

**Comment by HerrDave** [comment]
Fear Aura buff name is now red
