### ISSUE TITLE
Sentinel tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1064]
- [x] Archer doesn't mention Shadowmeld ability
- [x] Archer says it has Aimed Shot, but it has Barrage
- [x] Hunter's Hall does not mention Sentinel Fortifications or ship upgrades, and refers to "Weapon Upgrades" when it should be "Forged Weaponry"
- [x] War Academy says it researches Sentinel, but it doesn't
- [x] War Academy doesn't mention Wind Walk research
- [x] Huntress says it has Evasion, but it doesn't
- [x] Huntress says it can learn Sentinel, but it starts with it
- [x] Sentinel Embassy says it has Ancestral Spirits, but it doesn't
- [x] Ancestral Spirits says it gives hit points back to the "Ancient", but the caster is not an Ancient
- [x] Sentinel Enclave tooltip doesn't mention Full Scale Escalation
- [x] Moonhunter says it has Paralysis, but it really has Shadow Strike
- [x] Corrosive Strike shares an icon and function with Acid Bomb but does not have the same name
- [x] Moonhunter Master Training says "Mark the Spot", should be Faerie Fire
- [x] Priestess says it can learn Light Burst, but it is actually Rain of Light
- [x] Priestess Adept Training says it teaches Astral Healing, but it is actually Dispel Magic
- [x] Hippogryph Rider tooltip doesn't mention Wind Walk
- [x] Chimaera tooltip says it can learn Lightning Barrage, but it can't (it probably should have it - a bug?)
- [x] Hunter Tower tooltip doesn't mention it can upgrade into Improved Hunter Tower
- [x] Guild Ranger tooltip says it has no abilities, but it has two
- [x] Tyrande tooltip says she has Starfire, but she has Rain of Arrows
- [x] Maiev tooltip doesn't mention Hunt Aura
- [x] Hunt Aura buff is named Speed Aura, and the tooltip refers to itself as SpeedAura
- [x] Naisha tooltip is improperly structured
- [x] Amara tooltip is improperly structured
- [x] The "Drive Them Back" quest says you get Jarod, but it only allows him to be summoned. It also does not refer to him by his full hero name
- [x] Jarod Shadowsong's ability list in his tooltip is wrong
- [x] Blood Fury erroneously shares an icon with Vampiric Aura
- [x] "Spellbook and Maiev Event" has no extended tooltip
- [x] Priestess of the Moon tooltip does not mention Shadowmeld or Resistant Skin
- [x] Elune's Gaze says it turns "each unit in the target area" invisible, but it has no targeting reticule
- [x] Naisha's Divine Hymn is mechanically identical to Resurrection but has a different name and icon (which it shares with Heal)
- [x] Warden tooltip does not mention Shadowmeld, Elune's Grace, or Resistant Skin
- [x] Elune's Infusion doesn't mention that it affects Redeemed Highborne
- [x] Moonhunter says it can learn Elune's Grace, but it starts with it
- [x] Improved Hunter Towers' "Bounce Attack" erroneously shares an icon with True Sight
- [x] "Bounce Attack" describes the tower as a Runestone, but it is a Hunter Tower
- [x] Hunter Tower and Improved Hunter Tower tooltips don't mention Bounce Attack
- [x] Naval Aura has no DISBTN icon
- [x] Maiev's Hunt Aura stacks with Naisha's Speed Aura, despite having the same name and icon _(this is unintuitive - if they are meant to stack they should have different names and icons, as they would have distinct mechanical functions)_
- [x] Improved Moonwells research says it gives 0 mana and 0 mana regeneration
- [x] Feathermoon Aura has an active icon (should be passive)
- [x] Feathermoon Aura buff has a passive icon (should be active)
- [x] Naval Aura has no DISPAS icon

**Comment by HerrDave** [comment]
Checking Amara's spell-kit, I can't find any spells which have identical tooltips

I'm not sure what you want us to do with Divine Hymn, unless you want it reverted to be the original yellow Resurrection

**Comment by YakaryBovine** [comment]
@HerrDave Interesting, I'll check that first one out.
Yes I'd just rename Divine Hymn to Resurrection and give it the same icon. The flavor differentiation isn't achieving anything interesting.

**Comment by YakaryBovine** [comment]
I have separated Amara's tooltip issues into another ticket since there are so many of them: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1229

**Comment by HerrDave** [comment]
Lightning Barrage (Chimaera: Sentinels) is listed as missing, but it is on the unit card

This appears to be a Techtree availability/restriction issue
