### ISSUE TITLE
Stormwind towers spells don't work

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1067]
![image](https://user-images.githubusercontent.com/119281194/212456829-23956a45-0a8b-43a2-80bc-f8449f865984.png)
![image](https://user-images.githubusercontent.com/119281194/212456832-58039a35-c816-42c5-af8e-d99b6cfa751a.png)

**Comment by YakaryBovine** [comment]
@linaz2009 Could you confirm that this is still a bug in the latest release?

**Comment by linaz2009** [comment]
> @linaz2009 Could you confirm that this is still a bug in the latest release?

![image](https://user-images.githubusercontent.com/119281194/213792205-57233f04-d300-4b7a-be91-704d9d2b3758.png)
Electric Strike works fine
Only Solar flare seems to not stop enemies from attacked, silence part works tho

**Comment by YakaryBovine** [comment]
Sweet. Duplicate of https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1164
