### ISSUE TITLE
Quel'thalas tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1068]
- [x] Architect says they have Improved Lumber Harvesting, but they don't
- [x] Palace tooltip doesn't mention Feint nor Full Scale Escalation
- [x] Farstrider tooltip doesn't mention Spell Resistance, Resistant Skin, or Precision Shots
- [x] Farstrider tooltip mentions Aimed Shot, which they don't have
- [x] Sunfury Warriors say they have Battle Experience, but they have Combat Experience
- [x] Magus Adept Training should say Siphon Mana, not Mana Siphon
- [x] Warlock tooltip says they have Summon Queen of Pain, but they have Summon Queen of Suffering
- [x] Arcane Annihilator tooltip says "Siege mode", should be "Siege Mode"
- [x] Sun Tower tooltip doesn't mention Improved Sun Tower upgrade
- [x] Improved Arcane Tower tooltip does not match tooltip formatting standards
- [x] Vareesa does not have a proper tooltip
- [x] Quel'danil Lodge quest does not indicate it unlocks Lor'themar
- [x] Incinerate Learn tooltip does not match proper hero learn formatting
- [x] Flame Burst Learn tooltip says it can damage "up to" targets
- [x] Flame Burst shares an icon with Flame Strike, but its effect is completely different
- [x] Wrath of the Blood elves says that it calls down "waves of falling light", but it actually looks the same as Starfall
- [x] Feint research tooltip doesn't mention Vereesa Windrunner
- [x] Suppression buff tooltip and icon is just Silence
- [x] Poisoned Arrow tooltip and icon is just Cripple

**Comment by HerrDave** [comment]
List complete!
