### ISSUE TITLE
Warsong tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1070]
- [x] Fortress doesn't mention Full Scale Escalation
- [x] "For the Horde!" buff is the same as Bloodlust
- [x] Burrow says it has Battle Stations, but it doesn't
- [x] Burrow doesn't mention Spiked Barricades
- [x] "To Tame a Land" doesn't mention it's required for Azerite Siege Engines
- [x] Siege Workshop says it train Azerite War Machines; should be Azerite Siege Engine
- [x] Kor'kron Elite tooltip doesn't mention Self-Bloodlust or Resistant Skin
- [x] Grunt tooltip doesn't mention Self-Bloodlust
- [x] Ignore Pain basic tooltip doesn't say [Level 1] or [Level 2] despite being upgradeable
- [x] Warlock's "Frenzy" spell is a mess; it has a wind icon, but the buff doesn't have a wind icon. The buff is visually identical to Bloodlust, but is not Bloodlust so it doesn't stack
- [x] Raider tooltip doesn't mention Pillage
- [x] Wind Rider doesn't mention To the Wind
- [x] For the Horde ability actually applies Mass Bloodlust
- [x] Iron Keeps say they only attack land, but they can attack air
- [x] Iron Keeps say they "throw massive boulders", but they shoot arrows
- [x] Grom's "Roar of Despair" buff is actually Disorientating Roar, and has a different icon
- [x] Roar of Despair says it reduces attack damage by 200% in the learn tooltip, but only 100% in the normal tooltip
- [x] Roar of Despair indicates completely different durations in the Learn versus the Normal tooltip
- [x] Battle Trance is mechanically identical to Avatar but has a different name (the buff is also named Avatar)
- [x] Battleshout has the same name and icon as Roar, but a completely different effect
- [x] Foreman Gibbs' tooltip is not to standard
- [x] Foreman Gibbs' Tinker ability just applies Rejuvenation
- [x] Foreman Gibbs' Aura of Durability applies a buff called Restoration Aura
- [x] The Wandering Brewmaster quest says it gives Chen, but it actually allows him to be trained
- [x] Chen's "Rounds For Everyone" ability erroneously contains "Level x" at the bottom of its tooltip
- [x] Jergosh's Curse of Flame shares an icon with Immolation 
- [x] Summon Zelemar says it attacks land units, but it attacks air as well
- [x] Curse of Flame extended tooltip describes "poison", but the ability has a fire theme
- [x] Curse of Flame's tooltip is "Elemental Fire" and the icon is different
- [x] Crossroads quest doesn't mention that it gives 2000 lumber
- [x] QuestChenStormstout has mechanics in its RewardFlavor
- [x] QuestCrossroads has mechanics in its RewardFlavor
- [x] QuestOrgimmar has mechanics in its RewardFlavor

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/212499094-5ec2b458-239c-4832-bdfa-8d113c47cc1a.png)
Doesn't mentin +2k lumber bonus

**Comment by YakaryBovine** [comment]
This issue may be related to the Iron Keep tooltip problem: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1082

**Comment by HerrDave** [comment]
Got as many as I could

The last 3 are on you, unless you can tell me where I can find the quest text locally :)

**Comment by YakaryBovine** [comment]
I'm re-opening this because the Warsong quest text changes aren't quite right.
The `RewardDescription` field should describe the game mechanics of what the quest gives you, e.g. "2000 gold".
The `RewardFlavour` field is completely different; it should describe only flavour, e.g. "Our troops have found an enormous treasure cache left behind by the Titans." 
@HerrDave feel free to re-assign those back to me if you've had enough of Warsong tooltips.

**Comment by HerrDave** [comment]
Aaahhh, my bad
