### ISSUE TITLE
Dalaran tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1072]
- [x] Dalaran buildings benefit from Improved Masonry, but they can't research it
- [x] Lumber Mills say they can receive lumber, but they can't
- [x] Refuge says they can train "Farmer, Whelp"; should be "Farmer/Whelp" to indicate that it is an option. Similar for upgraded versions
- [x] Conclave and Observatory says it has Replenish Mana, but it doesn't
- [x] Observatory tooltip doesn't mention Initiate Mages spell
- [x] Observatory doesn't mention Full Scale Escalation
- [x] Summon Initiate Mage buff name is Feral Spirit
- [x] Initiate Mage's Slow ability erroneously capitalizes "AIR"
- [x] Raise Earth says it lasts 20 seconds, but this is not true; it lasts until it dies, and it takes damage over time
- [x] Mage Armor buff gives no indication of what it does
- [x] Healing Shield buff has typos
- [x] Arcane Sanctuary says it researches Magic Sentry, but it doesn't
- [x] Scout Tower tooltip doesn't mention Magic Sentry
- [x] All tower tooltip says it can learn Magic Sentry, but it starts with it
- [x] Arcane Tower says it can learn Reveal, but it starts with it
- [x] Improved Arcane Tower tooltip is not standardized
- [x] Antonidas' Frostfall says it calls down waves of ice, but it is just Starfall
- [x] Jailor Kassan tooltip is not to standard
- [x] Kassan's Binding Shackles' buff tooltip is Aerial Shackles
- [x] Medivh's Surge of Power buff tooltip doesn't indicate what it does
- [x] Draconic Spire says it trains Dragonspawn, but it trains Blue Dragonspawn
- [x] Judicator says it has Chain Heal, but it has Healing Wave

**Comment by HerrDave** [comment]
Conclave & Observatory techtree issue - Replenish Mana
