### ISSUE TITLE
Stormwind tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1073]
- [x] Clear the Outskirts quest doesn't mention it unlocks Summon Garrison
- [x] Keep tooltips don't mention Call to Arms
- [x] Peasant tooltip doesn't mention Call to Arms
- [x] Castle doesn't have Call to Arms, but Keep does
- [x] Stormwind Champion, Outrider tooltip mentions Animal War Training, but this is not an ability
- [x] Castle doesn't mention Full Scale Escalation
- [x] Poisoned Spear is autocast but doesn't have an autocast icon
- [x] Poisoned Spear says it does poison damage, but this is not a real type of damage
- [x] Spearman, Marshal tooltip mentions Runic Strength, which doesn't exist
- [x] Gunship's Repair Crew has an autocast icon, but it's not autocast
- [x] Scout Tower doesn't mention Magic Sentry
- [x] #1143
- [x] Improved Arcane Tower tooltip is not to standard
- [x] Guard Tower says it can learn Magic Sentry, but it can't
- [x] Conveyance Aura and Earth Bind learn tooltips have extra hotkey indicators
- [x] Champion's Hall says it enables Devotion Aura on Stormwind Keep, but Devotion Aura is available from the start
- [x] Conjurer tooltip says it has Firestorm, but it has Lightning Storm
- [x] Lightning Storm has a different name from Monsoon despite being mechanically identical
- [x] Solar Flare Ritual erroneously shares an icon with Flare
- [x] Electric Strike erroneously shares an icon with Mana Flare
- [x] Solar Flare buff is Silence, should be Solar Flare
- [x] Conveyance Aura learn tooltip uses the passive icon; should be active

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/213792649-d13ef5c1-386c-4665-a271-dd5097b08db2.png)
![image](https://user-images.githubusercontent.com/119281194/213792660-5bb546e1-e2fe-4e06-b990-fbebc3a1d678.png)
Firestorm into lightning storm wasn't updated

**Comment by HerrDave** [comment]
Wurk complete!
