### ISSUE TITLE
Ironforge tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1075]
- [x] Masons say they can learn Improved Lumber Harvesting, but they can't (they should probably have it)
- [x] Great Hold doesn't mention Full Scale Escalation
- [x] Thane says it has Avatar, but it has Perfect Avatar
- [x] Thane doesn't mention Resistant Skin
- [x] Perfect Avatar buff is just Avatar
- [x] Perfect Avatar tooltip says the unit will take "no damage", but this is not true; they only get 97% damage reduction from it
- [x] Forgeworks says it can research Magic Sentry, but it can't
- [x] Forgeworks doesn't mention Improved Swig
- [x] Forgeworks can research Improved Lumber Harvesting, but Mason's don't have the Improved Lumber Harvesting ability (they probably should have it)
- [x] Scout Towers say they can upgrade to Keep Towers, but they can't
- [x] Rifleman says it can be loaded into Keep Towers, but Keep Towers don't exist
- [x] Rune of Shielding shares an icon with Inner Fire, but does something different
- [x] Gryphon Aviary doesn't mention the Gryphon Superior Breed research
- [x] Guard Tower and Improved Guard Tower says it has Magic Sentry, but it doesn't
- [x] Improved Cannon Tower tooltip is not to standard format
- [x] Magni Bronzebeard's train tooltip is his entire title, should be his proper name
- [x] Lightning Streak has the same icon as Forked Lightning
- [x] Flamebeard tooltip is not to standard
- [x] Baelgun Flamebeard's train tooltip is just "Flamebeard"
- [x] Mithril Plated Armor doesn't mention that it applies to Baelgun Flamebeard
- [x] Dagran's tooltip says he can learn "Inferno Strike, Rain of Fire, Brilliance Aura, Ritual of Fire". Should be "Rain of Fire, Ritual of Fire, Brilliance Aura, Firestorm"
- [x] Dagran's Rain of Fire shares an icon with Dagran's Firestorm
- [x] Dagran's Firestorm is flavoured as fire, but it is actually just Monsoon visually
- [x] Mustering Hall doesn't mention Armor Penetration Rounds

**Comment by HerrDave** [comment]
"Wurk complete!"
