### ISSUE TITLE
Iron keeps have an air attack which can't damage air units

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1082]
https://imgur.com/a/7MbGFRR

**Comment by YakaryBovine** [comment]
As far as I can tell they're actually not intended to attack air, as per the bullet point in https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1070.

**Comment by linaz2009** [comment]
But they have special anti-air attack and warsong doesn't have other towers

**Comment by YakaryBovine** [comment]
Ok, makes sense. Re-opening.
