### ISSUE TITLE
funny pathing with portal

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1083]
https://imgur.com/a/8oTaQyf

**Comment by linaz2009** [comment]
legion was summoned in dalaran
exodar was invading Argus

**Comment by YakaryBovine** [comment]
@linaz2009 Not sure if there is anything we can do about this but I'll log it for now.

**Comment by SebastianTanoni** [comment]
@YakaryBovine im not so sure, it might be related to #1097

**Comment by SebastianTanoni** [comment]
it seems like the portals get set wrong? like maybe they are using the same variable?

**Comment by YakaryBovine** [comment]
Can't see how this could be related to #1097. I think we should just put this down to bad Waygate pathing when the Exodar is open in a particular position in Argus.
