### ISSUE TITLE
The "Quel'danil Lodge" quest doesn't give control of the base

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1084]
![image](https://user-images.githubusercontent.com/119281194/212559094-26e3be01-9509-4fdc-b189-99ba38adf381.png)

**Comment by YakaryBovine** [comment]
@HerrDave @SebastianTanoni Looks like in the rework, the QuelDanil Lodge region wasn't moved to cover the Quel'danil Lodge units: 
![image](https://user-images.githubusercontent.com/8995690/212560261-9c6eaaf3-d6ec-4d30-9c70-4ebc28c7ff91.png)

**Comment by HerrDave** [comment]
My fault, I didn't move the region

Fixed
