### ISSUE TITLE
Legion portal bugged, cant enter argus

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1097]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Can you add more details to this?

**Comment by SebastianTanoni** [comment]
@YakaryBovine yes, when the legion is summoned, the outside portal doesnt seem to work. You can enter argus through the outside legion portal after the legion is summoned

**Comment by YakaryBovine** [comment]
Ok, if that's the case it sounds like a me issue.

**Comment by YakaryBovine** [comment]
Tried this a few times in singleplayer, seems to work fine in normal circumstances. Will need a replay or reproduction steps to go any further. Happy for someone else to take a look at it.

**Comment by SebastianTanoni** [comment]
@YakaryBovine ok will close it for now
