### ISSUE TITLE
Abilities based on Monsoon are not sufficiently differentiated from Monsoon

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1100]
There are a few abilities based off Monsoon, such as Eredar Warlock's Rain of Fire. These used to have custom visual effects. These were broken by Blizzard in a Reforged patch, so they now all just look like Monsoon. Since they now look like and have the same visual effect as Monsoon, they should just be called Monsoon and have the same icon.

**Acceptance criteria**
 - All abilities derived from Monsoon are named Monsoon and have the Monsoon icon

**Bonus points**
Many of these units aren't themed properly to have Monsoon, like Eredar Warlocks. The editor doing this could potentially find or make alternative abilities that fit... Like for Warlocks, just use actual Rain of Fire.

**Comment by YakaryBovine** [comment]
Reopening with new information. This is a bug so shouldn't ever be closed as stale.
