### ISSUE TITLE
Death Knight tooltip says Black Strike, but it is actually Black Arrow

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1152]
Yes, but clearly Death Knight's do not attack with arrows? How do we fix this

**Comment by YakaryBovine** [comment]
@SebastianTanoni That's fine. The ability can be called Black Strike.
The problem is that the Death Knight tooltip says "Black Strike", and the ability itself is called "Black Arrow". Just rename the ability to "Black Strike".
