### ISSUE TITLE
Delete Scarlet Crusade base in Northrend

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1161]
![image](https://user-images.githubusercontent.com/8995690/213846311-11f2f5c0-187c-448d-bd83-731f3c14bed8.png)

**Comment by SebastianTanoni** [comment]
We could add Lordaeron events back using this base, that would be a lot of terrain work to redo, maybe we should ask Herrdave wether to remove it or not?

**Comment by YakaryBovine** [comment]
Yeah that's a tough one... I'm guessing you would keep this base for sure if we do Scarlet content? In which case I think we do just have to icebox this again.

**Comment by HerrDave** [comment]
Base removed

I think there is a much better way to do it in the future, but the current one we'd be better without
