### ISSUE TITLE
Solar Flare does not actually remove the ability to attack

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1164]
Solar Flare says that it prevents attacks but it actually only silences.
Just need to add Special to the Attacks Prevented category.
![image](https://user-images.githubusercontent.com/8995690/213850883-2a7d1ca5-ea4e-42e9-bd4b-fc4dc797d0c5.png)

**Comment by linaz2009** [comment]
It used to give 100% chance to miss in JASS iirc

**Comment by YakaryBovine** [comment]
Yeah not sure what happened there. This is purely an object editor spell so I assume the change was intentional but maybe the tooltip wasn't updated?

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/213898493-0022110d-1295-4c9b-8a42-8234cf91b341.png)

i dont see why it doesnt work

**Comment by SebastianTanoni** [comment]
change field to special
