### ISSUE TITLE
Scourge reanimated dead are not dispellable

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#1167]

**Comment by YakaryBovine** [comment]
@TracyTheBoy Which spells is this referring to?

**Comment by linaz2009** [comment]
Kel'thuzad's animate dead probably

**Comment by TracyTheBoy** [comment]
Yea it is either that or the Frozen Throne one or maybe both.
I just noticed that I couldn't dispel the reanimated crypt fiends when I was fighting scourge in NR.
