### ISSUE TITLE
Warsong Shadowpriest spawns at silly place with Warsong Expedition

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1185]
![image](https://user-images.githubusercontent.com/119281194/214915048-7be5bad1-118a-4e7a-8889-b81d2fb9c878.png)

**Comment by linaz2009** [comment]
I think he got here through illidan's portal

**Comment by linaz2009** [comment]
https://wc3stats.com/games/339972
this is replay if someone wants to dig out the issue

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/214930026-8492acb3-44bf-4b67-be49-58551e6a8b0d.png)
Found the issue, he spawns with expedition

**Comment by YakaryBovine** [comment]
Thankyou!
