### ISSUE TITLE
Goblin player can see observer pings

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1189]
![Screenshot_39](https://user-images.githubusercontent.com/8995690/215002191-7025d9dd-7e27-4ca8-994d-bb1d66b3c047.png)
![Screenshot_38](https://user-images.githubusercontent.com/8995690/215002201-f941e9ef-1eb5-4f2d-bb8a-92f82cd15585.png)

**Comment by SebastianTanoni** [comment]
This one is pretty wierd

**Comment by YakaryBovine** [comment]
No kidding 💫
