### ISSUE TITLE
Meredith Waycrest issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1254]
- [x] Meredith is erroneously registered as Malygos in LegendDalaran.cs (this is an example of why we should use the Constants system)
- [x] Meredith is not registered in LegendKultiras.cs
- [x] Siren's Scream is gramatically incorrect. Should be "Unleash a powerful sonic scream, putting all enemy units within a radius of x to sleep for y seconds."
- [x] ^Similar typo exists in the Extended Tooltip.
- [x] Wraith Form trivial typo; "lasts" should be capitalized
- [x] Sonic Scream's "Sleep" buff says that attacking it will wake it up, but this is not true
- [x] Wraith Form's buff is Metamorphosis, should be Wraith Form
- [x] Wraith Form gives Resistant Skin, which is completely pointless on a hero
- [x] Meredith's Extended tooltip should say "Wraith Form", not "Wraith's Form"
- [x] Wraith Form says it gives 10 extra hit points, but it doesn't. Both of her forms have 10 hit point regen baseline

**Comment by YakaryBovine** [comment]
Note to self: I failed to pull the second set of changes so I need to review this review...

**Comment by YakaryBovine** [comment]
Sorted

**Comment by YakaryBovine** [comment]
Some of these issues weren't fixed so re-opening

**Comment by SebastianTanoni** [comment]
changing the default sleep tooltip fixed it
