### ISSUE TITLE
Player can type -obs after the Lich King hero dies to avoid their stuff going hostile

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1285]
If they do this, it gets transferred to their ally instead.

**Comment by YakaryBovine** [comment]
I think if I just pull https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1186 forward this won't matter anymore.

**Comment by TracyTheBoy** [comment]
fixed in https://github.com/AzerothWarsLR/WarcraftLegacies/commit/bfd1fdd7c8d72dc6f5a001d0c2d5cbb227b88aca
Destroying a hivemind and typing -obs now have the same behaviour so doing this brings no advantage anymore
