### ISSUE TITLE
-limited doesn't work for last elite

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1294]
https://imgur.com/a/pqsSqgD

**Comment by YakaryBovine** [comment]
@linaz2009 Do you have a replay or something for this? Can't figure out where the issue is. Could be the command or it could be that the Paladin limit is broken somehow.

**Comment by linaz2009** [comment]
> @linaz2009 Do you have a replay or something for this? Can't figure out where the issue is. Could be the command or it could be that the Paladin limit is broken somehow.

How to replicate https://imgur.com/a/RewjsDf

**Comment by TracyTheBoy** [comment]
solved in ed89c1f3a8784bb01af300141e6164f77ee36592
