### ISSUE TITLE
Extraordinary lag shortly after casting Mass Unholy Frenzy on the Tuskarr creep camp near the Scourge starting base

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#1314]
Hopefully this is related to https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1313. Otherwise gonna be a hard one to investigate. Seems to be somewhat sporadic, though I can replicate it every time.

**Comment by SebastianTanoni** [comment]
The lag seems fixed, i changed a few numbers and i have not been able to reproduce it since
