### ISSUE TITLE
Eye of Sargeras spells don't have proper grid hotkeys

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#1328]
![image](https://user-images.githubusercontent.com/119281194/219955352-d0537b9d-f5ae-49c2-a1b1-13622e966e6c.png)
![image](https://user-images.githubusercontent.com/119281194/219955355-7dddda9f-3d20-49ce-a7f4-fa61f03965d8.png)
![image](https://user-images.githubusercontent.com/119281194/219955358-d94cb75c-b32e-4bc7-9f0e-d88517bc8ff8.png)
![image](https://user-images.githubusercontent.com/119281194/219955360-05e63647-ad2f-425a-9bba-f681d9f6e5c8.png)

**Comment by Technopig1992** [comment]
fixed with #2000
