### ISSUE TITLE
The great grammar and spelling review

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#1476]
We keep getting feedback about various event messages and quest texts being wrong.

This issues serves as a reminder to check for those things whenever anything in the c# projects is being edited and correct it if necessary.

**Comment by YakaryBovine** [comment]
This is a beautiful thing, but with the compiler tool I think we have an ongoing solution to the problem. All new content will be reviewed by me. I'll eventually get through all old content, in theory.
