### ISSUE TITLE
Trying to use the -complete cheat triggers the -clear command

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#1497]

**Comment by Technopig1992** [comment]
I think its typing anything that starts with -C will clear messages 

![image](https://user-images.githubusercontent.com/127978232/226760156-1667bbec-d15a-416c-9853-bc7105db452f.png)

**Comment by TracyTheBoy** [comment]
closed by 3587e60894e42864270ecd9c765b96956e545dc4
