### ISSUE TITLE
Add a self-destruct button to Waygates and the Focal Demon Gate

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#154]
Both Waygates and Focal Demon Gates need to be destroyed by their owners in some circumstances. Make that easier by giving them an instant self-destruct ability.

**Comment by SebastianTanoni** [comment]
@YakaryBovine if you create just a self destruct spell, il give it to every unit that could benefit

**Comment by YakaryBovine** [comment]
It seems as though this was already done.
