### ISSUE TITLE
Implement a crisis picking system

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#1586]
Requirements:

- a menu that can be opened like powers or artifacts
- Each card represents one faction
- Each card ha one button that when clicked selects the faction
- Each card has a headline 
- Each card needs space for flavour text, tips and other information that isvaluable to the player deciding on their faction
- Cards can be added dynamically to the menu (through quests for example)
- Once a faction has been picked it is removed from the menu 
- Once a faction has been picked the menu is made unavailable to the player

**Comment by YakaryBovine** [comment]
As far as I know this is no longer relevant as Crises are not a feature.
