### ISSUE TITLE
SW caster building has a bunch of upgrades after he obs

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1688]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Does this bug still exist? If so how is it reproduced?

**Comment by SebastianTanoni** [comment]
It was player reported,  no method given and I haven't heard from it again.

**Comment by SebastianTanoni** [comment]
@YakaryBovine

**Comment by Ripzss** [comment]
i Would assume this would no longer be an issue with the new Refund System where caster buildings gets removed now

**Comment by YakaryBovine** [comment]
Sweet, thanks. Let's remove it.
