### ISSUE TITLE
Forsaken/cult quest

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1707]
- [ ] get a base in northrend
- [ ] brew the plague?
- [ ] infiltrate the north alliance
- [ ] capture the sunwell
- [ ] destroy capital palace 
- [ ] unlock valkyrs?

**Comment by YakaryBovine** [comment]
At this stage these look more like brainstorms than planned work! If you need these notes somewhere, Google Docs is probably a better place for it.
