### ISSUE TITLE
No Timer and turn counter display

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#183]

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/201360173-81227513-ab18-43be-a90d-cbbe4d6b826c.png)

**Comment by SavanticIO** [comment]
This is a super easy one unless the plan is to redo the timer system. @YakaryBovine If the plan is just to get this one working again then I'll grab this one.

**Comment by YakaryBovine** [comment]
@SavanticIO Yep, sounds great.
