### ISSUE TITLE
Cannot rescue the trolls and orcs on Frostwolf Starting island

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#184]
Completing Riders of the Storm is meant to give you control of every unit on Frostwolf's starting island, _but_ it should also be possible to rescue the groups of Trolls and Orcs just by approaching them, like in the campaign.

As far as I recall this is implemented in GUI in the vJASS version.

![Frostwolf 1](https://user-images.githubusercontent.com/47048283/201360084-8c22d6e8-f968-4de8-95dc-4785ecceb88b.PNG)

**Comment by SavanticIO** [comment]
@SavanticIO I'll pick this one up as well as some of the other Frostwolf stuff. I'll tag you in the others

**Comment by YakaryBovine** [comment]
@SavanticIO tomorrow I will get you properly assigned to all of these and add more details to the tickets. But consider them reserved for you. Sorry, hectic night

**Comment by YakaryBovine** [comment]
Updated description.
