### ISSUE TITLE
Goblin Quest - Explosive Engineering 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#1888]
![Warcraft_III_17_05_2023_15_51_15](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/e734603a-b869-41a3-92d5-df8664f62df5)

Altar shows as numerical value again

**Comment by SavanticIO** [comment]
Hey. I've made a PR to fix this one

**Comment by Technopig1992** [comment]
excellent work
