### ISSUE TITLE
Long march completion text is wrong

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#189]
![image](https://user-images.githubusercontent.com/47048283/201361458-dc188f5b-ba32-4fa5-982b-275f194face0.png)

**Comment by SavanticIO** [comment]
Also what should the text be? Some thing like 'The Tauren clans have joined the Horde.'?

**Comment by YakaryBovine** [comment]
@SavanticIO Sorry for the late reply, had a very rough day yesterday.
I imagine that we want something flavourful and cool representing the idea that, yeah, the Tauren clans have joined the Horde. It's up to you if you want to try being creative about it or go with something simple as stated. Either works.
