### ISSUE TITLE
The Great Legacies Optimisation Challenge 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#1898]
The recent blizzard patches have effected FPS and stability across all maps, whilst this is something we wait on blizzard to fix it has made it clear that some other maps were less effected than others. Due to this I believe there are a few simple things (all be it tedious) we can do it to increase performance across the board.

- [x] Optimise imported audio files. 
- [ ] Reduce dot particles and particle emitters on most heavily used spells and missile animations 
- [x] Optimise all custom BLPs.
- [x] Optimise all vanilla BLPs.
- [ ] Optimise all vanilla MDX's.
- [ ] Optimise all custom MDX's.  
- [ ] Optimise all models for zoomed out game play - no one plays at the default zoom in view so a lot of the detail in models can be pointless and a waste of performance, simplifying the geometry of some models will help this.
- [ ] Edit models with unneeded detail and remove it (for example Acolytes have face detail but wear hoods so it never seen!)
- [x] Check for and remove any hidden objects in/and or under the map that are not needed.
- [ ] Remove as many destructibles as possible without changing the look or feel of the map (for some reason destructible hog a fair amount of resource in large numbers) - changing some into doodads will help. 
- [ ] Check for every un-harvestable tree in the map and replace with a doodad model (same reason as above).
- [ ] Where a structure or piece of scenery is made of multiple doodads we need to merge these together into one model wherever possible.

Other things to possibly look at:

- [ ] Use the Hive World Editor to create direct pathing. Pathing blockers were always necessary but resource heavy as warcraft pathing engine is inefficient and causes unit stutter and stress on the system drops FPS heavily. With the HWE we can create direct pathing and remove all pathing blockers (except dynamic ones) this should improve FPS significantly when factions are near food cap and also prior.
- [ ] Reduce map size - not sure if this one will be possible but a smaller map size would lead to increased performance, moving the continents closer together and removing any dead blocked off space would see an improvement.
- [ ] Reducing regions -Having multiple regions stresses the pathing engine fairly heavily and messes up unit pathing on top of that - all though Regions are pretty much a must for triggers and events if and when possible we should look at minimising our use of regions and removing any redundant ones.
- [ ] Forcing a set zoom distance - the best and most efficient way to play these macro maps is viewing the entire large fight on screen at once - no more no less. However players will always zoom out to much further values when able despite the FPS drop. If we find a distance that suits for most if not all it may be worth coding it in the distance and FarZ distance for all.

**Comment by YakaryBovine** [comment]
@Technopig1992 You all good if I convert this into a Wiki page? It's on-going rather than a single discrete item so it's not really suitable as an Issue.

**Comment by YakaryBovine** [comment]
I've made this into a Wiki page here: https://github.com/AzerothWarsLR/WarcraftLegacies/wiki/Optimization-goals
