### ISSUE TITLE
Wierd text for the tomb of sargeras quest

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#190]
![image](https://user-images.githubusercontent.com/47048283/201361803-ff4505e9-0ffc-4c6c-a08d-15c96ebb876d.png)

**Comment by SebastianTanoni** [comment]
Also should require lvl 10 on the hero to open the quest

**Comment by TracyTheBoy** [comment]
@YakaryBovine I'll take this
