### ISSUE TITLE
Helm of domination drops on a bad spot when the frozen throne dies

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#191]
![image](https://user-images.githubusercontent.com/47048283/201362581-33253938-e389-4924-ba14-20a897a1e385.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/373f41e09fb498b3c78c973b649ad77d46edbf4b.
