### ISSUE TITLE
Implement the Frostwolf Clan's Pack Kodo mechanic from the live vJASS version of the game

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#192]

**Comment by SavanticIO** [comment]
@YakaryBovine

**Comment by YakaryBovine** [comment]
FYI this isn't implemented and bugged; it's just not implemented at all. You can refer to the vJASS version for an idea of how it works. Just start as Frostwolf and train a Pack Building from any structure.
