### ISSUE TITLE
Villagers are transformed during loading (if scourge player is absent probably)

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#194]
![image](https://user-images.githubusercontent.com/47048283/201364089-d28305d5-c659-4e9f-9e1c-3cf5e13bd7ec.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/0d70816cc011d66574651a3a392057021315dc56.
