### ISSUE TITLE
Have a button next to powers called decisions? where you can pick paths and such. 

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#196]
![image](https://user-images.githubusercontent.com/47048283/201364399-1fc4863b-1548-42b5-b134-f9086f03b4bb.png)

Its wierd to have them come from the blacksmith.

Having a window for meta choice would be cool

**Comment by YakaryBovine** [comment]
Sure, I like it.

**Comment by YakaryBovine** [comment]
Don't think there are enough paths to justify the work here ATM.
