### ISSUE TITLE
Capital City was not given to me

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#197]
![image](https://user-images.githubusercontent.com/47048283/201365791-94b2fa46-9848-4039-b66e-da39668eef15.png)

I compleated 2 quests at once, defense of stranhbrand and Hearthlands

**Comment by SebastianTanoni** [comment]
It is currently hostile

**Comment by TracyTheBoy** [comment]
@YakaryBovine I'd like to do this.
