### ISSUE TITLE
The Exile Quest is missing (Lordaeron

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#198]
Its the quest to unlock Mograine

**Comment by TracyTheBoy** [comment]
@YakaryBovine I'd like to do this.

**Comment by YakaryBovine** [comment]
FYI @SebastianTanoni this quest wasn't actually missing, it just only gets added when the Living Shadow quest gets completed. We could look at changing that if it's not clear.

**Comment by SebastianTanoni** [comment]
I completed the other one and i didnt have the exile

**Comment by TracyTheBoy** [comment]
I'm not sure if there is still work left do here now. 
Is it still not working after the changes I submitted?

**Comment by YakaryBovine** [comment]
It is; I think Sebas made his comment without being aware of your fix. I'll mark it as closed and triple-check it myself. Thank you Tracy.
