### ISSUE TITLE
Undercity entrance are visible before Undercity Exists

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#199]
![image](https://user-images.githubusercontent.com/47048283/201366270-97094f7d-e4e8-4a30-b44b-cc311e017ecd.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/0317ded0b6e8d7b82311b40a8a6a16ed13b88dcb.
