### ISSUE TITLE
King therenas dropped the stormwind Crown too

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#200]
![image](https://user-images.githubusercontent.com/47048283/201366372-c2e7234d-ebdf-4689-a6d9-8615dc84682b.png)

**Comment by TracyTheBoy** [comment]
@YakaryBovine I'd like to do this.

**Comment by YakaryBovine** [comment]
For clarity: Terenas is meant to just drop the Crown of Lordaeron when the Capital Palace dies. This is a pretty funny bug.
