### ISSUE TITLE
Gilneas Shipyard in GilneasUnlock Region 3 

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2023]
Shipyard gets moved to shallowpart so outside of the Region on game start, players are also unable to build shipyards in the shallow part aswell  Picture for Reference 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/37cf8156-a213-44a1-ab27-73cae2a58603)

**Comment by SebastianTanoni** [comment]
Fixed shipyards being unbuildable in the shallow waters, cant seem to fix the teleporting shipyard.

Possible tries: delete it, save, then put a new one

**Comment by SebastianTanoni** [comment]
the shipyard wins, we cantmove it, except for slight visual imperfection,its not the end of the world so il close the ticket

**Comment by YakaryBovine** [comment]
I might as well give this a crack before we give up.

**Comment by YakaryBovine** [comment]
Yeah I reckon I'm prepared to throw in the towel on this one too lmao
