### ISSUE TITLE
Open gate work, but dont change visually

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#203]
![image](https://user-images.githubusercontent.com/47048283/201368675-398bf0e9-9f9c-47b3-9554-bfb19ce0a940.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/c4626024864e6a7b26be3d7408911471342a1b98.
