### ISSUE TITLE
Move Quel'Thalas refugees spawn location

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2031]
Change spawn location to new outpost in Hinterlands. 

Also add an escape boat to the shore maybe?

Option 1 - Have moved the Quel'Danil Lodge and incorporated this into the outpost - Would need to remove the Quel'Danil quest and make the lodge count as a T3.

Option 2 - Replace the lodge with a normal T3, moving the lodge back to its original position and leave the Quel'Danil quest the same

**Comment by SebastianTanoni** [comment]
TODO: Make queldanil quest have a fail condition. If you lose sunwell,you fail the quest, and gain some units in queldanil lodge. Or you can normally complete it and unlock stuff as usual
