### ISSUE TITLE
Demon Gates - Fel Horde

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2034]
Remove limit of 1 on upgraded Demon Gates - Currently you can cheese it anyway and after playing a few games vs 4 Terrorguard gates it does not seem like an issue.

Slightly reduce spawn time for upgraded demon gates

**Comment by YakaryBovine** [comment]
As discussed around here (https://discord.com/channels/1161755984759378100/1161755985363353643/1174112508257255464), Sebas will change the system to avoid this bug occurring. As a result it is now a Feature ticket and must go in a major version.
