### ISSUE TITLE
Changed CP armor to Unarmoured from Medium 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2036]
May need to give them something to nerf piercing damage - 150% against Unarmoured.

**Comment by SebastianTanoni** [comment]
Location of file: MacroTools/ControlPointSystem/ControlPointManager

**Comment by SebastianTanoni** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/0b7fa6c9-1707-4190-80f4-afc5ff2ef3b6)

**Comment by Ripzss** [comment]
Armour Changed from Medium -> Unarmoured

Added Passive Tower Resistance
Piercing damage reduction of 50%
