### ISSUE TITLE
Mass Frost Armour ability for Obsidian Statues 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2037]
Have already created:

Mass Frost Armour ability 
Mass Frost Armour dummy ability 
Added Mass Frost Armour to Scourge spell setup ( see screenshot )

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/dff99169-355f-4100-9210-846cb35a1374)

However the it does not seem to work in game

**Comment by SebastianTanoni** [comment]
TODO: test if it works now, made a small change to the code
