### ISSUE TITLE
Fix the SA/NA bridge 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2040]
When i first started playing it was on a patch where the bridge was there but bugged and you could not walk over so it got removed and never got added back. Is there a reason we cant add it back at X turn?

**Comment by SebastianTanoni** [comment]
@SavanticIO I think you mentioned wanting to do this on discord?

**Comment by SebastianTanoni** [comment]
il do this!
