### ISSUE TITLE
Mass Bloodlust and bloodlust stack 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2043]
- Make sure Mass Bloodlust and Bloodlust share the same buff, and thus do not stack
 - Rename Self-Bloodlust to Frenzy, ensuring it has a custom icon. It should stack with Bloodlust

**Comment by YakaryBovine** [comment]
@SebastianTanoni What would you prefer here?
1. Mass Bloodlust and Bloodlust stack as they currently do, but Mass Bloodlust is renamed to something else so that it's clear that it stacks.
2. Mass Bloodlust and Bloodlust no longer stack.

**Comment by SebastianTanoni** [comment]
For clarify sake, it's okay for me

**Comment by YakaryBovine** [comment]
> Sounds good. I just make sure the buffs are matching right ? 

Yup that's correct
