### ISSUE TITLE
Certain Control Points sometimes display odd behaviour

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2057]
Lands End Beach - Troll start 

Gadgetzan - Goblin Start 

Storm Peaks - Forsaken Start 

Surramar - Illidan Start 

All the above CPs seem to not behave correctly in certain situations . Animation missiles from Crypt Fiends  stack and do not disappear

Storm Peaks  - Very high regen always , missiles stack 

Lands End Beach - Very high regen always , missiles stack 

Gadgetzan - Missiles stack, only high hp regen when Trolls are picked .

Surramar - Missiles stack

**Comment by Technopig1992** [comment]
possibly some sort of correlation with them being Starting CPs assigned to a faction.

**Comment by YakaryBovine** [comment]
I'll fix this.
