### ISSUE TITLE
Add a timer to indicate the time until the game starts

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#207]
![image](https://user-images.githubusercontent.com/47048283/201369903-e8e2b6e2-c248-46b4-a923-43034cceadb1.png)

**Comment by SavanticIO** [comment]
I think this might have been done as part of adding back the game timer.

**Comment by YakaryBovine** [comment]
@SavanticIO Looks like it. Nice catch.
Closed by #273
