### ISSUE TITLE
Chat command - send gold/wood

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2074]
For some factions such as Legion & KulTiras, you cannot receive resources from any players . 

In some situations the entirety of the night elf team cannot trade between themselves . 

Issues like this pop up regularly are seem to always be slightly different , no idea of the cause . 

A nice QoL change would be a send gold/wood chat command .

**Comment by YakaryBovine** [comment]
I'll do this: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2095
