### ISSUE TITLE
Ensure that all Gold Mines are the same distance from their starting Town Halls

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2096]
Currently, different factions need to train a different number of workers to saturate their Gold Mines. This isn't indicated anywhere, so they should be standardized.

**Non-exhaustive list of factions with too far out Gold Mines**
* Stormwind
* Lordaeron
* Kul'tiras
* Quel'thalas
* Dalaran
* Ironforge

**Comment by YakaryBovine** [comment]
Unless there's a very good reason to do otherwise, I'd suggest standardizing worker saturation at 5 workers since that's how melee handles it.

**Comment by SebastianTanoni** [comment]
Todo: set all workers speed to 190

Make sure town centers are 4 orthogonal squares or 3 diagonal squares from their gold mine
