### ISSUE TITLE
Opening options sometime just freezes the game???

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#211]
![image](https://user-images.githubusercontent.com/47048283/201371991-d83bc04e-75ef-462b-b1c7-607227171a09.png)

Only way to exit this is to alt-f4 and then cancel

**Comment by YakaryBovine** [comment]
Found a post on Discord suggesting that this only happens after opening the Options menu after the game has been paused, so this shouldn't be possible in multiplayer.
