### ISSUE TITLE
Sunfury clarity issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2118]
- [x] Astromancer caster upgrade icon is water themed, should be astro. Could also just be something generic... As long as it's not water.
- [x] Suppression buff is just Silence
- [x] Flamekeeper Cremate has no autocast icon
- [x] Warlock Monsoon indicates it has multiple levels, but it doesn't
- [x] Arcane Ward shares an icon with Sentry Ward
- [x] Aura of the Reaver has a passive icon, and the name is awful
- [x] Arcane Bombardment should not share an icon with Starfall
- [x] Solarion's tooltip says her abilities are "disruptive", but actually she's a pure damage dealer
- [x] Kil'jaeden's Fear Aura buff doesn't indicate what it does, and the tooltip should be red, not green
- [x] Kil'jaeden's Finger of Death has a completely different effect to Finger of Death... Is actually just Forked Lightning
- [x] Energy Grid's buff name is Spirit Touch
- [x] Energy Grid shares an icon with Spirit Touch, despite having a different effect
- [x] Energy Grid's tooltip says nothing about how its mana cost works
- [x] Void Reaver button position is wrong

**Comment by YakaryBovine** [comment]
Todo: look at quests.

**Comment by YakaryBovine** [comment]
Basic issues I have fixed:

 - Bloodwarder
 - Dashing Phoenix
 - Phoenix (renamed to Summon Phoenix)
 - Arcane Absorption
 - Holding
 - Covenant
 - Training Quarter
 - Lyceum Arcanum
 - Astromancer
 - Monsoon
 - Warlock
 - Ancient of the Arcane
 - Arcane Ward
 - Tempest-Forge
 - Energy Wagon
 - Skyship
 - Improved Sky-Fury Tower
 - Seeds of Regrowth
 - Orb of the Arcane
 - Crystal Strike (renamed to Finger of Death)
 - Summon Goliathon
 - Consumed by the Void
 - Kil'jaeden
 - Blood Knight Squire
 - Scorpion

**Comment by Technopig1992** [comment]
https://www.hiveworkshop.com/threads/btnmanaward.57337/ < Arcane Ward icon.

**Comment by Technopig1992** [comment]
Arcanum Basin for Void Well?

**Comment by YakaryBovine** [comment]
> Arcanum Basin for Void Well?

Pretty solid I think!
