### ISSUE TITLE
The gold indicator is wrong, i probably have 140 gold, not 14

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#212]
![image](https://user-images.githubusercontent.com/47048283/201373329-a0af7b9c-acc3-4c17-abce-77de20506700.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/376fdd0b06a7468d302e5e64a08af43c5ef9e764.
