### ISSUE TITLE
Ancient of Arcane 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2127]
Plays the Birth animation of an Ancient when trained 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/fc249405-2a7f-4fb0-aca0-a039a7fdfe65)

**Comment by Technopig1992** [comment]
@HerrDave i imagine this is due to the model still having the birth animation of the normal ancient model. I can give a go at removing it , but if you know an easy way xD

**Comment by YakaryBovine** [comment]
Doesn't look like we're going to spend the modeling time on this and it's just behaviour that we've come to expect from Ancient models, so closing.
