### ISSUE TITLE
Gold rework

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2130]
To do:

Reduce all elites cost to 50

Reduce all gols mines by half

Reduce all cp income

**Comment by SebastianTanoni** [comment]
Remaining to do: Creep gold change and name of control points

**Comment by SebastianTanoni** [comment]
@YakaryBovine i will need your help to make those last 2 things happen. I looked at the cp config and i dont know how i will pull it off.

There is also the problem that a TON of quest have cps in their objectives. Which includes their full name: Ashenvale_15_gold

So if we change the name via code, will it update the constant??? I might have no choice to edit all of them in game, il wait for you to read this.

**Comment by YakaryBovine** [comment]
@YakaryBovine Yup I can sort those two things out. 
Yes we will have to manually update all of the changed Constants references.

**Comment by YakaryBovine** [comment]
I have split out those requirements into my own ticket: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2168
