### ISSUE TITLE
Baron Rivendare

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2134]

**Comment by Technopig1992** [comment]
- Currently has a passive and an aura as abilities, feels a bit underwhelming as a result. 
- Ultimate is a Roar for attack and defence and the values feel quite low.
- Ramstein made spell immune / un-dispelable

**Comment by YakaryBovine** [comment]
@SebastianTanoni @Ripzss @Technopig1992 Are any of you planning to work on this one? Would like to get it narrowed down to 1 assignee.

**Comment by SebastianTanoni** [comment]
I wasn't planning on it originally
