### ISSUE TITLE
Buff animate dead numerical values for dk

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2155]

**Comment by Technopig1992** [comment]
DK animate dead to retain abilities.

**Comment by Technopig1992** [comment]
Animated units gain extra hit points ?

**Comment by SebastianTanoni** [comment]
@Technopig1992 is this still needed balance wise?

**Comment by Technopig1992** [comment]
If this has been done to Kels animated dead I would leave this as is. Just need to lower the mana cost and it's too high atm .
