### ISSUE TITLE
Give some heroes starting levels

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2158]
- [x] Ticondrius
- [x] cairne
- [x] tyrande
- [x] vashj
- [x] nobundo
- [x] Gallywix

**Comment by Technopig1992** [comment]
Ticondrius 1>4
 cairne 3>4
 tyrande 1>2
 vashj 1>1
 nobundo 1>4
 Gallywix 1>5
