### ISSUE TITLE
Move the Titanforging research from the Great Forge to buildable Blacksmiths

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#216]

**Comment by YakaryBovine** [comment]
@SebastianTanoni I'm guessing this is to make Titanforging more interesting/viable. I wonder if it would be more effective to just buff the Titanforge passive and add more passive options?

**Comment by SebastianTanoni** [comment]
Thats a good option too! I had an idea about it, what if when you titanforge an item for a hero, that hero gets some bonus exp too, on top of better passives?

**Comment by YakaryBovine** [comment]
Here's the way I see it:
**What is Titanforging meant to accomplish?:** It's meant to make Ironforge have the best artifacts, as part of their flavour as legendary blacksmiths and explorers.
**Why does Titanforging not accomplish that?:** The bonuses gained from Titanforging suck, so players that use it still don't get to feel like master blacksmiths.

So it seems simple; just make the bonuses better. Any other fix means the intended theme would still not be satisfied, even if it would make players do the mechanic.

**Comment by SebastianTanoni** [comment]
ok yup! i agree

so lets do this:

make the upgrades much better, and give a cooldown on it (if there isnt)

i dont want the ressource cost to be a wall. So time can be one. Players will be rewarded to periodaclly go forge their stuff
