### ISSUE TITLE
The Twilight Grove quest description dose not fit Objectives (Gilneas) 

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2161]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/a2d9a738-f4d9-414e-ac99-ba1ad7e1dbee)

**Comment by YakaryBovine** [comment]
@SebastianTanoni Any thoughts on this? It's not going to be possible to just rewrite the flavour text, because Goldrinn has no connection to Wyrmrest Temple. Is there a more lore-appropriate objective that will work? What was the issue with the Shrine of Goldrinn objective?

**Comment by SebastianTanoni** [comment]
I wanted gilneas objective to stay in the north alliance duel. Because of 8v8. If it happened that your ally is the night elves, you get goldrinn requirement literally turn 2

**Comment by SebastianTanoni** [comment]
So I need an objective that is linked to the fight with Legion and scourge in some way
