### ISSUE TITLE
Programmatically alter creep gold and Control Point names according to Sebas' specifications

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2168]

**Comment by SebastianTanoni** [comment]
For control points: if we assume they were in a base 5, they are now in base 4.

10 -> 8

15-> 12

20-> 16

25 -> 20

50 -> 40

**Comment by SebastianTanoni** [comment]
Creeps specification will be posted here when I get home!

**Comment by SebastianTanoni** [comment]
Giold formula :

Level of the creep = X

Gold Bounty base = 4X

Gold Bounty Number of Dice = X

Gold Bounty Sides per Die = 3

**Comment by YakaryBovine** [comment]
All done in `dev`.
