### ISSUE TITLE
Tear it down quest did not complete

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#217]
![image](https://user-images.githubusercontent.com/47048283/201392773-7282b1ea-a381-4d0b-9c63-1ad8b180a11c.png)

Even though grom is alive, the quest objective did not complete

**Comment by SebastianTanoni** [comment]
Tear it down on completion description doesnt mention foreman gibb

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/9bd3e32b1ad68d84c32cc017dcaac5fbcd437cb2.
