### ISSUE TITLE
The draenei exodar is still invulnearble even though all draenei bases are destroyed

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#222]
![image](https://user-images.githubusercontent.com/47048283/201394859-c4f9c538-9f00-46d0-81d7-6ef4c101711e.png)

**Comment by SavanticIO** [comment]
@YakaryBovine

**Comment by YakaryBovine** [comment]
I think there's a Fel Horde quest that's meant to make this vulnerable? Not sure.
