### ISSUE TITLE
Kalimdor Balance Notes 

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2232]
Link to document:
https://docs.google.com/document/d/16JyX0eippDbmpvdYk0CcjrDSf_Yi0OKVB0UJ2kqq1hY/edit

**Comment by YakaryBovine** [comment]
@Ripzss Is this document still relevant? If not can we close?

**Comment by Ripzss** [comment]
You can close this @YakaryBovine
