### ISSUE TITLE
All T1 and T2 Town Halls tooltips are missing their ability to train elites in their tooltips

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2259]
- [x] Frostwolf
- [x] Stormwind
- [x] Quel'thalas
- [x] Scoourge
- [x] Ironforge
- [x] Warsong
- [x] Fel Horde
- [x] Dalaran
- [x] Gilneas
- [x] Goblin
- [x] Zandalar
- [x] Lordaeron
- [x] Druids
- [x] Draeneei
- [x] Illidan
- [x] Sunfury
- [x] Sentinels
- [x] Kul'tiras
- [x] Legion

**Comment by YakaryBovine** [comment]
Also it seems a bit odd that T1 and T2 capitals can train elites but not upgrade them.

**Comment by SebastianTanoni** [comment]
> Also it seems a bit odd that T1 and T2 capitals can train elites but not upgrade them.

We could add thr upgrades, and make them require t3

**Comment by YakaryBovine** [comment]
I think that's the right move for sure.

**Comment by SebastianTanoni** [comment]
Lordaeron, frostwolf, scourge, druids done

**Comment by SebastianTanoni** [comment]
I create a branch for this T1_T2_tooltips
