### ISSUE TITLE
Destroying Stormwind keep while it is neutral promps legendary creep death message

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#226]
![image](https://user-images.githubusercontent.com/47048283/201395321-1c8ed3ad-4d9e-4da8-ba98-add49513a5f7.png)

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this one.

@SebastianTanoni Should the 'LEGENDARY CREEP DEATH' message only appear if the unit is NEUTRAL_AGGRESSIVE?

**Comment by SebastianTanoni** [comment]
@SavanticIO yes, but more precily, it will never trigger on a building. Legendary creeps are always units or heroes

**Comment by YakaryBovine** [comment]
Closed by #367.
