### ISSUE TITLE
Shadow of Silverspine forest requirement is wrong, should be to defeat a dire wof, not a worgen

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#228]

**Comment by SebastianTanoni** [comment]
Picking the wrong dire wolf, need to use the location thing

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/95449ddd2cb3351f42eb1d960224d0b11acf3ea7.
