### ISSUE TITLE
The Highmountain Control Point is a hero

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2298]

**Comment by YakaryBovine** [comment]
Technopig's recent commit did not actually fix this

**Comment by HerrDave** [comment]
Should I pull from Main and merge the fix to that, or keep it in Dev?

**Comment by YakaryBovine** [comment]
> Should I pull from Main and merge the fix to that, or keep it in Dev?

From main please. This one is hotfix material, which is the only time we use main.
