### ISSUE TITLE
Legion succubus (heal caster) heal is too quick and upgraded version is melee

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2327]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/e0515938-3ed0-4f0c-b918-94eae8f58d0a)
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/7b69d4c6-6621-4b1f-88b6-4f8e9c96cc54)

**Comment by Technopig1992** [comment]
#2328  should fix
