### ISSUE TITLE
Oil Supply doesnt drain oil when transfering to transports

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#234]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Let's have a talk again about the goblin oil mechanics. I think it'd be great if we made more use of the Power system and devised something really easy to use.

**Comment by YakaryBovine** [comment]
Closing as this is not a bug anymore. Oil is automatically transferred between units now.
