### ISSUE TITLE
If Silvermoon is unlocked via OnFail  the player is unable to train Anasterian Sunstrider 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2342]

**Comment by YakaryBovine** [comment]
@Technopig1992 If this is considered a bug, then it affects all other quests that grant both a base and a hero. You might want to loop @SebastianTanoni in.

**Comment by Technopig1992** [comment]
@SebastianTanoni

**Comment by SebastianTanoni** [comment]
im not sure if this is a bug... its really how the feature are done now. Basically all rewards that are NOT base unlocks currently arent given if a quest fails. Only base are always given

**Comment by SebastianTanoni** [comment]
that behavior is there for every quest i think, so if its a bug or not would require further discussion

**Comment by YakaryBovine** [comment]
If you're happy with the current design then it sounds good to me, I'll close.
