### ISSUE TITLE
World Shamen Quest  not working correctly 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2347]
showing as 6/7 cps owned even when 7.

possible that it has something to do with FW and Illidan starting allied

**Comment by Technopig1992** [comment]
I checked and it still not working correctly in Great War

**Comment by Technopig1992** [comment]
The one CP that is not registering with the Quest is the Suramar CP - I think it has something to do with Frostwolf and Illidan starting allied

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/pull/2703
