### ISSUE TITLE
Duplicate Icons 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2362]
I will update this list . 

NA
- [x] Captain Falric / Captain
- [x] Uther / Paladins
- [x] Arthas Summons / Captains 
- [x] Sylvanis /Fastriders
- [x] Antonidas/Kirin Tor
- [x] Anasterian Sunstrider / Spellbreakers
- [x] Gilneas shotgunner
- [x] Protector
- [x] Cleric

**Comment by YakaryBovine** [comment]
Hey @Technopig1992 Lordsebas is gonna take this one!

**Comment by SebastianTanoni** [comment]
Gilneas shotgunner, protector, cleric

**Comment by YakaryBovine** [comment]
Think we can release North Alliance without this fix. Have marked it as a Bug though, so it should never go stale.
