### ISSUE TITLE
Grom Hellscream priority order 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2372]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/7c2a3a2f-380d-41b1-a15e-e2f692a20f49)

**Comment by SebastianTanoni** [comment]
cant fix that as far as i know, i think they are talking about the top left icons of heroes, not the actual control groups order

**Comment by SebastianTanoni** [comment]
and that cannot be fixed in anyway i know

**Comment by YakaryBovine** [comment]
It's technically possible if we mess around with moving unit ownership around. Will think about it.

**Comment by YakaryBovine** [comment]
Sebas is right that it's quite hard to fix and it's probably not worth the complexity to do so. Closing. Can re-open if someone is keen to work on it.
