### ISSUE TITLE
Siege Regen 0>3

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2398]

**Comment by YakaryBovine** [comment]
I think if we're doing this we need to look at the Repair Crew ability on Goblin and Stormwind mechanical units. It's there to indicate that that unit uniquely has HP regen. But if mechanical units can have HP regen anyway, no need for the ability.

**Comment by SebastianTanoni** [comment]
> I think if we're doing this we need to look at the Repair Crew ability on Goblin and Stormwind mechanical units. It's there to indicate that that unit uniquely has HP regen. But if mechanical units can have HP regen anyway, no need for the ability.

thats a good point. We removed troll regeneration in the past because it wasnt felt necessary to mention base hp as a passive icon. I think we should just do the same for those goblin units?

**Comment by YakaryBovine** [comment]
> > I think if we're doing this we need to look at the Repair Crew ability on Goblin and Stormwind mechanical units. It's there to indicate that that unit uniquely has HP regen. But if mechanical units can have HP regen anyway, no need for the ability.
> 
> 
> 
> thats a good point. We removed troll regeneration in the past because it wasnt felt necessary to mention base hp as a passive icon. I think we should just do the same for those goblin units?

Yeah I reckon so.
