### ISSUE TITLE
Victory condition is Enabled in Great War mode

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2438]
Also Great war is an option at the bottom now? make it the top selection again

**Comment by YakaryBovine** [comment]
@Ripzss Is this urgent as in like, should-release-fix today urgent?

**Comment by Ripzss** [comment]
No not really urgent it just spams the the screen with Victory iminent so its just annoying

**Comment by YakaryBovine** [comment]
Cool, I'll get it fixed.

**Comment by YakaryBovine** [comment]
@Ripzss Talked with Sebas and I think we're going to keep the new ordering, as it goes from "most supported" to "least supported". Unfortunate to do this by accident but if I fix the bug now I'll just end up changing to this order again in the future anyway.
I'll also be replacing Great War (9v7) with two proper 8v8 gamemodes, one for each configuration. That'll come in a major version.
