### ISSUE TITLE
When a player leaves, all his units get refunded and deleted

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#244]

**Comment by SebastianTanoni** [comment]
as opposed to only certain units, like elites and heroes, get removed and refunded

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this one

**Comment by SavanticIO** [comment]
I'm not sure this is an issue. As far as I can tell when a player leaves, all their units are refunded and their buildings are given to the remaining team members

**Comment by YakaryBovine** [comment]
@SavanticIO Really? I don't remember doing this... I'll check it out now.

**Comment by YakaryBovine** [comment]
@SavanticIO You are completely correct. Closing this is as it's already been done.
