### ISSUE TITLE
Spirits of ashenvale quest cannot be completed, upgrade building is wrong

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#245]
![image](https://user-images.githubusercontent.com/47048283/201404954-aded2c68-453f-4cec-b0ff-dd3a679ed2ea.png)

also, cenarius is trainable before it

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/c119762b2ff20e17a24ada362d446d52dde92de9.
