### ISSUE TITLE
Changing the StatsGoldBountyAwardedNumberOfDice on creep gold transformations results in no change

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2489]

**Comment by YakaryBovine** [comment]
From Vampirika: 
I think there are a couple anomalies but mostly seems okay actually:

Occulus hero (level 8) dropped 14 gold when minimum is 16.
Wraith below karazhan (level 6) dropped 48 gold when maximum is 30.

I think some of the issue is just the formula needs rejigging as could have this scenario:
Level 7 mob gives 14 gold (14-35)
Level 3 mob gives 15 gold (6-15)
However interestingly, when I implemented my level formula (basing off the gold one and which I'd like to think I got right as it worked for most creeps), there were a few that were unaffected:

Wraith lvl 6 (below karazan)
Makrura deepseer lvl 5 (all over but one is NE of jinthalor)
Revenant of the seas lvl 5 (outside tomb of sargeras)
Heretic lvl 5 (below caer darrow)

**Comment by vampirika** [comment]
@YakaryBovine I think this is resolved, as we found that some were not changed and heroes were not accounted for

**Comment by YakaryBovine** [comment]
Glad to hear it!
