### ISSUE TITLE
QuestWarnBase should make the Draenei bases neutral passive and vulnerable, not neutral passive and invulnerable

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#249]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Could you clarify how this is meant to work? Are the bases just meant to start Neutral Passive and _vulnerable_?

**Comment by SebastianTanoni** [comment]
> Correct, since if draenei is too slow, Fel Horde could destroy them still. If not, draenei could wait forever without unlocking them to lock fel horde

**Comment by SavanticIO** [comment]
@YakaryBovine looks like there are a few Draenei related issues. I'll take a look at those.
