### ISSUE TITLE
Add a function to make it easy to copy shared researches from one Faction to another

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2490]
When Lordaeron goes Scarlet Crusade, they experience several transformations, some of which may or may not be supported by the current system.

**Transformations**
* Quests change completely; all old quests should be gone and replaced by new ones
* Name changes (?)
* Color changes (?)
* Entire techtree changes

**Things that should not transform**
* Upgrades
* Ability levels

**Comment by YakaryBovine** [comment]
Sebas this is assigned to you so you can do the analysis step. Once you know what you need supported, assign it back to me.

**Comment by SebastianTanoni** [comment]
So quest completly change
the name and color change
The entire tech tree

Im not sure what ability levels is

Upgrades. so here is the tricky part, only the upgrades in the SharedFactionConfigSetup should be passed on! 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/df01aa6c-fd96-4d61-9516-d4ef18a02279)

**Comment by YakaryBovine** [comment]
Great. So I think you were right the first time then; we replace the player's faction completely, the same way it works now, and just have an extra function to transfer their researches. I did that with Ragnaros back in the day so should be easy enough.
