### ISSUE TITLE
Oil spawn in unbuildable location

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2499]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/a2e004e8-c0d2-4aa2-9fee-3e9016ab9c83)

**Comment by YakaryBovine** [comment]
Just need to make all the terrain in that area Rocks instead of the weird Tiles it currently has under it. Oil Rigs can only spawn on those tiles.
