### ISSUE TITLE
Velen is alive, but the quest is not completing

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#253]
![image](https://user-images.githubusercontent.com/47048283/201410953-64193d7c-165a-436f-8567-1a645bc1e9d9.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/fb25ebf394c6e0d639189fdcf8d915f04bc174f5.
