### ISSUE TITLE
Gold bounty migrations do not apply to certain units

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2538]
This results in those units giving the wrong gold bounty. The issue is that these units have no modifications, so the compiler doesn't load them. The fix is to modify the units in some way before running the compiler. 

* Wraith
* Makrura Deepseer
* Revenant of the Seas
* Heretic

**Comment by SebastianTanoni** [comment]
@YakaryBovine do you want me to do and modify 1 little thing for every creep that isn't modified its easy but slightly tedious

**Comment by YakaryBovine** [comment]
> @YakaryBovine do you want me to do and modify 1 little thing for every creep that isn't modified its easy but slightly tedious

That would be awesome!
