### ISSUE TITLE
Hotkey overlap 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2539]
Only one reported but a couple come to mind

- [x] Spike Barricades (some races)  / Navigation 
- [x] Observatory Restore Mana / Improved Forked Lightning 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/c9d60445-96c2-41ce-82f0-8c948d7c57ed)

**Comment by SebastianTanoni** [comment]
mana regen to Z

**Comment by Tehia** [comment]
Will look on that.
