### ISSUE TITLE
Make Illidan starting base change to his control after the neutrals have turned hostile

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#255]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Need a little more detail. When do the neutrals turn hostile? Is this part of a quest?

**Comment by SebastianTanoni** [comment]
A bunch of neutrals around the map start as player 16. Because i overload the neutrals hostile and passive.

So when the game starts, it picked every unit of player 15? whatever player number illidan is, and turned them neutral hostile.

After that is done, his starting base (ilidan's) need to be turned back to his control so he can play the game

**Comment by YakaryBovine** [comment]
Awesome, thankyou.

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this

**Comment by SavanticIO** [comment]
@SebastianTanoni What region is Illidan's starting base in? None of the names in the regions file make it super obvious

**Comment by SebastianTanoni** [comment]
@SavanticIO there might be no region, so someone will have to place it :) il do it in about 2h15!

**Comment by SebastianTanoni** [comment]
Name of the region: IllidanStartingPosition

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/pull/367.

**Comment by SebastianTanoni** [comment]
This was not fixed

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/81dee5de0fa04eaa0d78f5707430589567c70635.
