### ISSUE TITLE
Redo Rivendare's Army of the Dead so it doesn't use a dummy caster

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2553]
Don't need a dummy caster for this mechanic and dummy casters are relatively heavy to use.

**Comment by SebastianTanoni** [comment]
Im curious, we dont need dummy casters??

**Comment by YakaryBovine** [comment]
> Im curious, we dont need dummy casters??

Nah not for this, because we can just spawn the unit directly using code and apply the Summoned tag. Same as the SummonUnitOnDeath thing you used.
