### ISSUE TITLE
carrion swarm tooltip

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2566]

**Comment by YakaryBovine** [comment]
I touched Carrion Swarm last so I assume this one is mine. Would be good to know exactly what the issue is but I can look.

**Comment by Ripzss** [comment]
The tooltip on lvl 3 says it dose up to 900 dmg but max damage is 750

**Comment by YakaryBovine** [comment]
> The tooltip on lvl 3 says it dose up to 900 dmg but max damage is 750

Thanks!
