### ISSUE TITLE
Properly account for the non-presence of Dalaran in the North Alliance fight if Dalaran is not picked

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2570]
If Dalaran is not picked...
* Move the Book of Medivh to Gilneas City
* Make Dalaran buildings neutral passive instead of neutral hostile, but put some neutral hostile creeps in the middle so it's a proper creep camp

**Comment by YakaryBovine** [comment]
May also need to look at Scourge's intro text to see if it references Dalaran specifically.
