### ISSUE TITLE
"Captured" Capitals retain there abilities 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2582]
Other players can cast "For the Horde" on TB for example , Garrison on Capital

**Comment by YakaryBovine** [comment]
@SebastianTanoni Could you confirm whether or not this is intended?

**Comment by SebastianTanoni** [comment]
I don't mind either way. I think ideally they don't keep their abilities, but if that's hard to do, I'm happy with how it currently is.

**Comment by YakaryBovine** [comment]
It's a little tedious but not difficult, so I'll unassign for now and leave it up.
Instructions to fix:
1. Make a list of all capital abilities.
2. Go into player properties and disable those abilities for all players.
3. Go into faction configs and enable those abilities for the appropriate factions.
