### ISSUE TITLE
Quest The Culling Fails when Scourge kills Stratholme on Dev Branch

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2588]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/0bb9d588-1048-4585-b3d5-46c7d2b3157f)

**Comment by YakaryBovine** [comment]
Fixed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/b805452580a6cd86821ea0a40abb29d786a641c7
