### ISSUE TITLE
Lordaeron's bonus Gold Mines are not removed when Gilneas is picked

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2606]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Do you know  where the code for this is meant to be? Can't find how this was working.

**Comment by SebastianTanoni** [comment]
I don't remember doing this, but in any case with this version that shouldnt exist anymore.  The lordaeron gold mines are indépendant frkn wether dalaran or gilneas are picked
