### ISSUE TITLE
Remove weird gold mines from Dalaran config

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2607]

**Comment by YakaryBovine** [comment]
FYI Dalaran's config has been moved to the new Faction construction style, which you can find at `Faction/Dalaran.cs`. Lordaeron is still on the old style. Should still be pretty clear what to do!

**Comment by YakaryBovine** [comment]
Fixed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/d10132d77b3b5506b8e5fc24a3f442e5a183e31e
