### ISSUE TITLE
Double Arthas if lordaeron is reviving arthas when stratholme dies 

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2611]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/51693156-5e9d-464e-83f3-45e29d4f242e)

**Comment by YakaryBovine** [comment]
@SebastianTanoni I think you just need to reduce the object limit to 0 for living Arthas when the quest is completed.
