### ISSUE TITLE
Make it clear in the Plague of Undeath quest text that it only moves units from Northrend

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2624]
"Army" is a bit of a vague term and players seem to assume it only teleports units from Northrend.

**Comment by SavanticIO** [comment]
I’ll take this one. Do we actually want to update the functionality to only do Northrend units if that’s what most players are expecting?

**Comment by SavanticIO** [comment]
The code has the region to take units from as "Regions.Northrend_Ambiance" so are players just exaggerating, is that region bigger than it should be or is there actaully a bug?

**Comment by YakaryBovine** [comment]
> The code has the region to take units from as "Regions.Northrend_Ambiance" so are players just exaggerating, is that region bigger than it should be or is there actaully a bug?

Interesting... OK. So I think everything is working as intended, and we _actually_ just need to make clear in the quest text that it only takes units from Northrend. I'll update the ticket name.

**Comment by YakaryBovine** [comment]
Fixed by SavanticIO.
