### ISSUE TITLE
Stop Ghouls that are in the process of harvesting from being teleported by Plague of Undeath

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2625]
Feedback tells us that having all Ghouls being teleported is annoying because they tend not to be in Control Groups, so they block the player's real army. We should be able to exclude Ghouls that are currently harvesting lumber using the `GetUnitCurrentOrder` native function.

**Comment by SavanticIO** [comment]
I’ll grab this one.
