### ISSUE TITLE
Add a delay time to Dreadlord's Dark Summoning spell

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2629]
**Success criteria:** 
When cast, Dark Summoning teleports 12 units in the target area to the caster after a delay.

**Bonus points**
1. The delay is based on the distance from the caster to the target.
2. If the Dreadlord dies mid-transit, kill a percentage of the transiting units.
3. The visual effect is well-telegraphed, so it's clear where the units are about to land. The Diamond of Summoning ground effect could be good for this.

**Decisions to make**
Should the units arrive at the caster after the delay, or at the location the caster cast the spell at?

**Comment by YakaryBovine** [comment]
The cast time can be achieved just in the Object Editor. However Dreadlords have no channel animation (I think), so we'll need to find an alternate way to show that the spell is being cast so it can be interrupted.

**Comment by YakaryBovine** [comment]
Actually it's probably more feasible to have a transit time, like the real Diamond of Summoning, rather than having a cast time. 
Basically: change Dark Summoning to work like vanilla Diamond of Summoning, just not bugged.

**Comment by YakaryBovine** [comment]
Bonus feature: if the Dreadlord dies mid-transit, kill a percentage of the transiting units.

**Comment by YakaryBovine** [comment]
Bonus feature 2: if the units travel in a straight line from Argus, that implies Argus is closer to SA than it is to NA. Which is cosmological nonsense. Some alternate path of travel if they come from Argus would be fun.

**Comment by YakaryBovine** [comment]
@SavanticIO You get first dibs of this if you want it, since you made the original spell being modified. If you're not keen, I'll take it.

**Comment by SavanticIO** [comment]
Yeah I'll have a go at it

**Comment by YakaryBovine** [comment]
> Yeah I'll have a go at it

Awesome. I think the easiest thing is going to be to use the Buff class. The rest of it should be in the ticket description but let me know if you need any more info.

**Comment by YakaryBovine** [comment]
Thinking about it again - if the effect is not attached to the caster, you're better off with a Hazard object. Unfortunately the Hazard system is something I made so it's less reliable than Buff, but it should be OK.
