### ISSUE TITLE
When Warsong leaves the game, they get control of the Crossroads instead of it turning hostile

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2632]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/974bb766-4603-4957-9750-b61020c12bb0)
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/54096a7d-b57d-4ece-a664-d5e46f1c3d36)

**Comment by SebastianTanoni** [comment]
When ANY player obs??

**Comment by YakaryBovine** [comment]
> When ANY player obs??

Just when Warsong leaves the games (including going obs). I've updated the title to reflect.
