### ISSUE TITLE
When a quest that grants a hero is failed, grant the hero anyway but apply a severe experience penalty

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2633]
**Provisional list of heroes acquired with base quests**
- [ ] Anastarian 
- [ ] Rend 
- [ ] Velen

**Comment by YakaryBovine** [comment]
As part of this ticket, make a list of all heroes which are acquired alongside a base so we don't miss anything.

**Comment by YakaryBovine** [comment]
For me: make an example based on the Anasterian one and attach it to this ticket.

**Comment by YakaryBovine** [comment]
@Technopig1992 Keen to do this in 3.11?

**Comment by YakaryBovine** [comment]
Doesn't look like there's any enthusiasm to do this so just going to close it!
