### ISSUE TITLE
When doing obs as goblin some gunners can be selected.

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2641]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/37e4bed4-6c98-418b-82e4-e7700056003c)
I assume this is Gunners spawned from like Shredders/tanks etc.

**Comment by YakaryBovine** [comment]
Let's just scrap this I think, it's inconsequential and quite difficult to fix.
