### ISSUE TITLE
When Gilneas is picked you cant pick up book of medivh as legion nothing on destroyed field

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2642]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/65b224dc-d767-4d11-816b-b218aee13c86)

**Comment by YakaryBovine** [comment]
@Ripzss Is this in `dev` or beta1?

**Comment by Ripzss** [comment]
@YakaryBovine this was in a beta1 game

**Comment by YakaryBovine** [comment]
> @YakaryBovine this was in a beta1 game

Cool, might be fixed already but I'll double-check.

**Comment by YakaryBovine** [comment]
Fixed in https://github.com/AzerothWarsLR/WarcraftLegacies/commit/fef3db4b43451d01d3462a4a11774a8d9be306a8
