### ISSUE TITLE
Revert changes to Warlock's Bloodlust ability

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2647]
This ability used to be called Windfury, but was renamed to Bloodlust at some point. Bloodlust is the wrong name because Bloodlust gives movement speed and this doesn't.

**Acceptance criteria**
* Rename the ability to Windfury
* Give it a wind-themed icon with Autocast border
* Ensure Warlock Adept Training is updated with the same icon, and its tooltip should reference Windfury
* Warlock's Caster Upgrade tooltip should reference Windfury
* Update the buff to have the same name and icon, and ensure the buff tooltip says what the ability actually does

**Comment by Tehia** [comment]
I think I'll can do it with a little help. Will sit on it later in this week.

**Comment by Technopig1992** [comment]
@Tehia good one to sink your teeth into , feel free to ping me for assistance

**Comment by YakaryBovine** [comment]
Unassigning this as Tehs is currently unable to edit. If anyone can pick it up that'd be great, otherwise I'll get to it one day.

**Comment by Technopig1992** [comment]
I can pick this up

**Comment by YakaryBovine** [comment]
Unassigning everyone from this as it looks like nobody is working on it - it's still a bug though so if anyone's keen to do it go ahead.
