### ISSUE TITLE
Reduce zombie tankiness

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2664]
Zombies are too tanky for free/trash units. It deters doing the hearthglen quest and is a nuisance to deal with as a lot spawn from caludrons/stratholme.
suggestion to lower hp and maybe armour.

**Comment by YakaryBovine** [comment]
I added the Hearthglen Zombies so I could fix that part. Don't really care what the creep camp is, just need to have some Undead there for flavour reasons. But sounds like there's a broader issue so I'll leave it alone.

**Comment by vampirika** [comment]
Yup, nothing against zombies in Hearthglen, just at the moment zombies in general are too tanky. Might take one out of hearthglen as well though

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/pull/2670
