### ISSUE TITLE
Adjust terrain/trees to avoid scourge tp getting stuck in stratholme

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2665]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/1f05ec1f-e703-47e3-ae45-2cac0e6c55cc)
Using a scroll on the citadel in stratholme can easily cause units to get stuck behind the nearby trees.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/pull/2670
