### ISSUE TITLE
Tooltips and typos - ongoing list 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2667]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/888aea4e-fb5e-4cdc-9998-552c3c218409)

**Comment by YakaryBovine** [comment]
Fixed this.
We should avoid using Issues to maintain ongoing lists of anything; Issues should be closeable, and we're never going to fix every tooltip. Listing tooltip issues would be great though, maybe just do it on the Wiki, Discord, or Google Docs.
