### ISSUE TITLE
Add full support for both 8v8 game mode variations

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2668]
- Remove Great War (7v9)
- Add two variants of 8v8 which each reflect the setup of a real 8v8 game

**Comment by YakaryBovine** [comment]
@Technopig1992 or @Ripzss could you add the two 8v8 setups as comments here please?

**Comment by Ripzss** [comment]
Teams can be following
NA/FH + Horde or Night Elf
SA/Evil + Horde or Night Elf

**Comment by YakaryBovine** [comment]
> Teams can be following
> 
> NA/FH + Horde or Night Elf
> 
> SA/Evil + Horde or Night Elf

Oh that's 4 combinations, right?

**Comment by Ripzss** [comment]
> > Teams can be following
> > NA/FH + Horde or Night Elf
> > SA/Evil + Horde or Night Elf
> 
> Oh that's 4 combinations, right?

Yep

**Comment by YakaryBovine** [comment]
@Ripzss @Technopig1992 Ok I'm losing my mind trying to figure out how there are 4 combinations here - reading it again it seems like there are only 2. These are the only two game modes, right?
 - NA, FH, Horde vs. SA, Evil, Night Elf
 - NA, FH, Night Elf vs. SA, Evil, Horde

**Comment by Technopig1992** [comment]
😂 correct , had to read it three times to be sure but correct!
