### ISSUE TITLE
Cthun caster 2 model improvement

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2669]
https://www.hiveworkshop.com/threads/arachnathid-optimized-scorpion.329358/

**Comment by YakaryBovine** [comment]
I think this one belongs in the Google Drive? 😆

**Comment by SebastianTanoni** [comment]
> I think this one belongs in the Google Drive? 😆

nono this is a ticket, its not a model dump, its a change im going to do!
