### ISSUE TITLE
Investigate ways to reduce overall unit count without impacting gameplay terribly

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2729]
Legacies has a lot of units, which has a massive impact on FPS. Maybe there are ways to reduce unit count without badly affecting gameplay. For instance, maybe spammable units like Ghouls could be somewhat less spammable?

**Comment by vampirika** [comment]
Initial thoughts, most include compensating with valid power increase. E.g. half units, double attack/hp etc.

Low impact / easy implementation:

- Zombies spawned.
- Garrison summons.
- Plague units, specifically necromancers.
- Fel summons.

High impact / medium or hard implementation:

- Workers
- Creeps and their summons.
- Neutral buildings.

**Comment by YakaryBovine** [comment]
> Initial thoughts, most include compensating with valid power increase. E.g. half units, double attack/hp etc.
> 
> Low impact / easy implementation:
> 
>     * Zombies spawned.
> 
>     * Garrison summons.
> 
>     * Plague units, specifically necromancers.
> 
>     * Fel summons.
> 
> 
> High impact / medium or hard implementation:
> 
>     * Workers
> 
>     * Creeps and their summons.
> 
>     * Neutral buildings.

Cutting down on all of those summons sounds like a great idea to me. @SebastianTanoni cool with that?

We have seperate investigation tickets for workers and neutral buildings:
- https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2722
- https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2725

**Comment by YakaryBovine** [comment]
Good investigation, follow-up here: #2734
