### ISSUE TITLE
Destroying multiple Artifacts crashes the game instantly

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#275]
Easy one to reproduce.
Type `-destroy Trol'kalar`
Then `-destroy Thunderfury`
The game will crash on the second command.

Note: you must have the Artifact menu open when using the second command.

**Comment by SavanticIO** [comment]
I tried reproducing this and after using both those commands the game didn't crash.

**Comment by YakaryBovine** [comment]
@SavanticIO Nice, that reveals something: you must have the Artifact Menu open when using the second command.
