### ISSUE TITLE
Negatively compensate units that previously had lumber costs

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2779]
With lumber removed, units that previously had lumber costs are now more resource efficient. These units are listed below, along with their lumber costs, so that they can be properly compensated for this buff. I have excluded heroes (who all previously costed 100 lumber) and creeps. Unsurprisingly, most of them are siege units or ships!

ebal: 65
ebsh: 150
edes: 50 
hbew: 35 
hbsh: 150
hdes: 50 
hgyr: 30 
hhdl: 40 
hmtt: 60 
hrtt: 60 
nba2: 120
ncco: 60 
nccr: 60 
nccu: 60 
nhyc: 70 
nmdr: 10 
nmys: 55
nnrs: 100
nsbs: 25
nser: 120
nssn: 20
nssp: 30
nwar: 60
nwgs: 14
nws1: 70
nzep: 100
obai: 35
ocat: 50
odes: 50
ojgn: 150
owad: 40
uarb: 60
ubdr: 200
ubsp: 30
udes: 50
umtw: 30
uobs: 50
uubs: 150
e008: 65
e00W: 80
e012: 75
e017: 65
e01B: 60
e01K: 80
e01M: 120
e01Y: 50
e01Z: 100
h00P: 80
h01P: 350
h03Z: 60
h04J: 200
h04O: 30
h04W: 150
h057: 75
h05V: 1000
h060: 300
h08T: 1000
h08X: 40
h08Z: 120
h091: 40
h09H: 100
h09J: 15
h0A0: 5
h0AA: 150
h0AM: 25
h0AN: 250
h0AO: 120
h0AP: 50
h0AQ: 65
h0AR: 20
h0AS: 20
h0AT: 20
h0AU: 20
h0AV: 50
h0AW: 50
h0AX: 50
h0AY: 75
h0AZ: 75
h0B0: 75
h0B1: 25
h0B2: 25
h0B3: 25
h0B4: 65
h0B5: 65
h0B6: 65
h0B7: 120
h0B8: 120
h0B9: 120
h0BA: 250
h0BB: 250
h0BC: 250
n006: 120
n02D: 150
n033: 120
n03L: 200
n04A: 150
n04L: 70
n051: 20
n057: 80
n05M: 20
n06N: 60
n07R: 70
n088: 150
n08C: 150
n08J: 80
n08K: 80
n09E: 25
n0B9: 100
n0CC: 100
n0CF: 25
n0CI: 120
n0CJ: 120
n0CK: 120
n0CL: 70
n0CZ: 600
n0D3: 10
n0E4: 40
n0E8: 200
o005: 50
o00I: 50
o01A: 50
o01O: 35
o02F: 50
o02U: 50
o04K: 50
o04S: 300
o04U: 50
o04W: 55
o06K: 150
u00J: 110
u01P: 50
u02F: 100
u02P: 100
u02W: 110

**Comment by SebastianTanoni** [comment]
- [ ] ebal: 65
- [ ] ebsh: 150
- [ ] edes: 50
- [ ] hbew: 35
- [ ] hbsh: 150
- [ ] hdes: 50
- [ ] hgyr: 30
- [ ] hhdl: 40
- [ ] hmtt: 60
- [ ] hrtt: 60
- [ ] nba2: 120
- [ ] ncco: 60
- [ ] nccr: 60
- [ ] nccu: 60
- [ ] nhyc: 70
- [ ] nmdr: 10
- [ ] nmys: 55
- [ ] nnrs: 100
- [ ] nsbs: 25
- [ ] nser: 120
- [ ] nssn: 20
- [ ] nssp: 30
- [ ] nwar: 60
- [ ] nwgs: 14
- [ ] nws1: 70
- [ ] nzep: 100
- [ ] obai: 35
- [ ] ocat: 50
- [ ] odes: 50
- [ ] ojgn: 150
- [ ] owad: 40
- [ ] uarb: 60
- [ ] ubdr: 200
- [ ] ubsp: 30
- [ ] udes: 50
- [ ] umtw: 30
- [ ] uobs: 50
- [ ] uubs: 150
- [ ] e008: 65
- [ ] e00W: 80
- [ ] e012: 75
- [ ] e017: 65
- [ ] e01B: 60
- [ ] e01K: 80
- [ ] e01M: 120
- [ ] e01Y: 50
- [ ] e01Z: 100
- [ ] h00P: 80
- [ ] h01P: 350
- [ ] h03Z: 60
- [ ] h04J: 200
- [ ] h04O: 30
- [ ] h04W: 150
- [ ] h057: 75
- [ ] h05V: 1000
- [ ] h060: 300
- [ ] h08T: 1000
- [ ] h08X: 40
- [ ] h08Z: 120
- [ ] h091: 40
- [ ] h09H: 100
- [ ] h09J: 15
- [ ] h0A0: 5
- [ ] h0AA: 150
- [ ] h0AM: 25
- [ ] h0AN: 250
- [ ] h0AO: 120
- [ ] h0AP: 50
- [ ] h0AQ: 65
- [ ] h0AR: 20
- [ ] h0AS: 20
- [ ] h0AT: 20
- [ ] h0AU: 20
- [ ] h0AV: 50
- [ ] h0AW: 50
- [ ] h0AX: 50
- [ ] h0AY: 75
- [ ] h0AZ: 75
- [ ] h0B0: 75
- [ ] h0B1: 25
- [ ] h0B2: 25
- [ ] h0B3: 25
- [ ] h0B4: 65
- [ ] h0B5: 65
- [ ] h0B6: 65
- [ ] h0B7: 120
- [ ] h0B8: 120
- [ ] h0B9: 120
- [ ] h0BA: 250
- [ ] h0BB: 250
- [ ] h0BC: 250
- [ ] n006: 120
- [ ] n02D: 150
- [ ] n033: 120
- [ ] n03L: 200
- [ ] n04A: 150
- [ ] n04L: 70
- [ ] n051: 20
- [ ] n057: 80
- [ ] n05M: 20
- [ ] n06N: 60
- [ ] n07R: 70
- [ ] n088: 150
- [ ] n08C: 150
- [ ] n08J: 80
- [ ] n08K: 80
- [ ] n09E: 25
- [ ] n0B9: 100
- [ ] n0CC: 100
- [ ] n0CF: 25
- [ ] n0CI: 120
- [ ] n0CJ: 120
- [ ] n0CK: 120
- [ ] n0CL: 70
- [ ] n0CZ: 600
- [ ] n0D3: 10
- [ ] n0E4: 40
- [ ] n0E8: 200
- [ ] o005: 50
- [ ] o00I: 50
- [ ] o01A: 50
- [ ] o01O: 35
- [ ] o02F: 50
- [ ] o02U: 50
- [ ] o04K: 50
- [ ] o04S: 300
- [ ] o04U: 50
- [ ] o04W: 55
- [ ] o06K: 150
- [ ] u00J: 110
- [ ] u01P: 50
- [ ] u02F: 100
- [ ] u02P: 100
- [ ] u02W: 110
