### ISSUE TITLE
Manually remove lumber costs from remaining researches

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2780]
I used automation to remove lumber cost from all researches, but unfortunately I had to skip some of them because it caused a crash. We'll have to do these manually, but there aren't many left. Here's the list:

Ruba
Rema
Rhac
Rhme
Remg
Rosp
Rhar
Roar
R00C
R03I
R09L
R05O
R08Q
R04R
R09W
R09X
R042
R092
R006

**Comment by SebastianTanoni** [comment]
- [ ] Ruba
- [ ] Rema
- [ ] Rhac
- [ ] Rhme
- [ ] Remg
- [ ] Rosp
- [ ] Rhar
- [ ] Roar
- [ ] R00C
- [ ] R03I
- [ ] R09L
- [ ] R05O
- [ ] R08Q
- [ ] R04R
- [ ] R09W
- [ ] R09X
- [ ] R042
- [ ] R092
- [ ] R006

**Comment by YakaryBovine** [comment]
As discussed on Discord, we're going to start keeping Issues open until they're merged into `dev` or `main`. I'll create a Github Project momentarily so you still have a good way of tracking your work in progress.
