### ISSUE TITLE
Warsong Balance Changes

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2788]
Currently, warsong roster is generally seen as weak and only heroes, elite squad and azerite engines are favoured. Horde was seen as weak even when grom mistakenly started at level 8, which goes to show how far they are behind now.

We should buff warsong remaining roster so they have more options and feel good to match up against NE team.

Units to look at:

- Blademasters
- Raiders
- Axethrowers
- Potentially casters, so warsong isn't SO reliant on fighting alongside Frostwolf for sustain. This would also begin to address some gripes about FW being "support faction" only.

**Comment by YakaryBovine** [comment]
Note that we'll probably do this in a minor version following the lumber removal version (it stays in the Next column, as a minor version is still part of the same overarching major version).

**Comment by vampirika** [comment]
Can we keep this open for now, would like some feedback from players to see if the changes made are enough or more are needed. Although could just do a new ticket too if that is preferable?

**Comment by YakaryBovine** [comment]
> Can we keep this open for now, would like some feedback from players to see if the changes made are enough or more are needed. Although could just do a new ticket too if that is preferable?

No, we should restrict Issues to things that can be completed through our own action rather than relying on external forces.
For your purposes I recommend opening a post in `player-feedback` on Discord. I did the same thing with plague removal and lumber removal.
