### ISSUE TITLE
Rescue Unit function Add a boolean to hide buildings too 

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#279]
make it so i can decide wether i want buildings to be hiden or not in the preparerescue function

**Comment by SavanticIO** [comment]
@YakaryBovine I'll be implimenting this and a few other overload methods to PrepareUnitsForRescue as a consequence of fixing #249

**Comment by YakaryBovine** [comment]
Awesome, that makes sense to me.
