### ISSUE TITLE
Constants Generator doesn't generate the correct name for Full Scale Escalation

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#283]
Running the "Generate Constants" function from the launcher results in the variable `UPGRADE_R04R_FORTIFIED_HULLS_UNIVERSAL_UPGRADE`. This isn't right, as you can see from the object editor screenshot below.
![image](https://user-images.githubusercontent.com/47048283/201500055-6a5b0db1-a9a2-4bee-b00c-d7ee93ccc2d9.png)

**Comment by YakaryBovine** [comment]
Don't think this is worth the effort; the bug isn't on my end and the problem is essentially cosmetic and constrained to one object.
