### ISSUE TITLE
Losing arthas doesnt fail line of sccession

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2843]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/47048283/cccb160e-0ad9-4c45-9d9c-6e6d377b1763)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/0579c1ac1759800c85822188c76ab5eedb600570
