### ISSUE TITLE
Figure out if Cthun is going to use undead boats or a special mechanic

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2846]
Right now C'thun has some placeholder ships registered so it can move units across the water. We're not sure yet how C'thun's naval mechanics will work.

If we give C'thun a special naval mechanic, we could remove those boats.
If we choose to keep the boats, we need to remember to go into the C'thun registry and update the object limits so use the `Constants` library rather than magic strings.

**Comment by YakaryBovine** [comment]
To elaborate on the description, it's these FourCC instances that need to be replaced with proper Constants:
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/69e6476d-2627-44b3-ae48-c57df7434caa)

**Comment by YakaryBovine** [comment]
We shall do this: #2914
