### ISSUE TITLE
North Alliance balance changes

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2855]
Gilneas:
1. Genn Roar damage bonus to 5/10/15/20% (it also gives armor and has best duration/cooldown and area of effect values out of all roars)
3. Worgen (the unit) damage reduced by 15
4. Cyclone Cannon attack speed to 0.4
5. Greyguard armor to 4, hit points to 1000 
reduce worgen hp by X

Scourge:
1. Increase Abomination hit points by 200
2. Remove Mechanical from Plague Titans
3. Reduce Gargoyle gold cost to 21

**Comment by SebastianTanoni** [comment]
Wyrm lower gold cost, slightly higher training time

**Comment by SebastianTanoni** [comment]
Make skeletons summon from DK not give Exp

**Comment by YakaryBovine** [comment]
> Make skeletons summon from DK not give Exp

I'm actually not sure which summon this is referring to, but summons in Legacies don't give experience in general anymore. So if something does that might be a bug.
