### ISSUE TITLE
Create Shifting Sand for Ouro

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2857]

**Comment by SebastianTanoni** [comment]
I set up the channel object in game, but i will need your help for the code part!

Heres what i need: WHen you cast the channel, it creates a dummy at the target, then it creates another dummy at the hero location that casts a mass teleport spell at the dummy where you casted channel.

The part i need help with is creating the dummy at the target

**Comment by YakaryBovine** [comment]
Closing this as per Discord
