### ISSUE TITLE
Ivory tower costs wood

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2858]
https://cdn.discordapp.com/attachments/553889462325870612/1227331823852589107/image.png?ex=662804d5&is=66158fd5&hm=9a300473726d0f8b4c64c628059bf0f346cf6db406614606aa630d4b33615715&

**Comment by YakaryBovine** [comment]
Let me do this one, I can write a script to catch all items. Didn't occur to me the first time.
