### ISSUE TITLE
Remove extra workers from quests that's not linked to a Gold Mine

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2869]
- [x] Frostwolf (Echo isle move to Thunder bluff Gold Mine)
- [x] Druids (base proteted by wildkin)
- [x] Sentinels (auberdine)
- [x] Stormwind (Goldshire, Lakeshire, Darkshire, NetherGarde Keep)
- [x] Scourge (Draktharon move it to the frozen throne Gold Mine)
- [x] Illidan (STV base unlock)

**Comment by Technopig1992** [comment]
With the Illidan STV ones I would either leave them or replace with a Town Hall in STV. Otherwise Illidans only workers come all the way from BT
