### ISSUE TITLE
Remove capability for legion dreadlords to summon boats onto land.

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2874]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/082ed0be-74d0-40c3-b131-3ba4af1be15b)
Dreadlords are able to summon boats to land areas, such as the example in image. 
Action: disable dreadlord summon on boats - water tile tag?

**Comment by vampirika** [comment]
I'll pick this up

**Comment by vampirika** [comment]
Inital find - amulet of recall does not summon boats but able to summon everything else. 
Proposed solution - make dark summoing use same targets as amulet of recall.

**Comment by YakaryBovine** [comment]
> Inital find - amulet of recall does not summon boats but able to summon everything else. 
> 
> Proposed solution - make dark summoing use same targets as amulet of recall.

Dark Summoning in Legacies is actually fully custom coded in C#. To my knowledge Amulet of Recall's boat exclusion is hardcoded into it, so not much help to us!
