### ISSUE TITLE
Ashtounge Mystic - Illidari 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2877]
Not benefitting from attack and defence ups; nor does it have an inventory 

https://media.discordapp.net/attachments/1228766598295191613/1228766599172067418/Warcraft_III_13_04_2024_18_30_03.png?ex=662d3d12&is=661ac812&hm=40406db2ab95aef1551f57bad31b1dfeb2ed92a725989ea6fa387295718be50f&=&format=webp&quality=lossless&width=1609&height=905

**Comment by vampirika** [comment]
I'll pick this up
