### ISSUE TITLE
System Error message if Fel horde is not in the game whilst Dark Portal activates 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2879]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/f32f1a13-501d-4177-9d17-7b125319ae33)

**Comment by YakaryBovine** [comment]
Not sure when this was fixed but appears not to be a problem anymore... At least, it's not clear how to replicate it if it is an issue. The Dark Portal quest has had a few changes recently.
