### ISSUE TITLE
Scarlet Crusade Bishop's Sanctify ability

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2884]
If the Bishop uses the Sanctify ability on itself , the effect becomes permanent 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/336b55e2-adb1-42f3-a20a-d88e8f154e56)

**Comment by YakaryBovine** [comment]
Duplicate of #2842 so I'll re-open that one (as it indeed wasn't fixed) and close this one.
