### ISSUE TITLE
Sentinel ability can't be cast because trees don't exist

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2887]

**Comment by YakaryBovine** [comment]
Probably need to replace this ability with something similar, e.g. Sentry Ward.

**Comment by Technopig1992** [comment]
will pick up , sentry ward with "overhead" Owl model looks pretty good aesthetically too

**Comment by YakaryBovine** [comment]
> will pick up , sentry ward with "overhead" Owl model looks pretty good aesthetically too

Sounds great, just have a refresh of the clarity standards here: https://github.com/AzerothWarsLR/WarcraftLegacies/wiki/Clarity-standards#abilities
In short, if the ability is mechanically identical to Sentry Ward (and Sentry Ward exists in the game, I don't remember if it does), it must share a name and icon with Sentry Ward.
