### ISSUE TITLE
Global quests shared by multiple players prints completion message for each player

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#289]
Easy to reproduce.
1. Make a quest global.
2. Add that quest to multiple factions
3.  Complete the quest on one faction
4.  Completion Text will show up for each faction that has that quest
![image](https://user-images.githubusercontent.com/93258020/201537302-7dff94dd-d929-4c42-901d-4956852c01e0.png)

**Comment by YakaryBovine** [comment]
Confirmed, good find.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/21719320c3c1fe291fb6e2b4e8fb29d689ffec5f. Bit of a half-assed solution but shared quests like this probably shouldn't be global anyway.
