### ISSUE TITLE
Skeletal Grunt 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2896]
Sketatal Grunts summoned for Fel Horde do not count as Undead ,

**Comment by YakaryBovine** [comment]
@Technopig1992 So, either I forgot to make them Undead when I made this ability, or someone intentionally changed them to non-Undead to deal with some ability interaction or another.
Either way I'll fix it, because undead units not being Undead is not valid!
