### ISSUE TITLE
Remove tunneling system remnants and boats from Ahn'qiraj

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2914]
* Workers can construct Tunnels (or Passages?)
* Units can enter any Tunnel, and then exit from any other Tunnel
* Workers can Deep Burrow, which lets them move anywhere - including underwater, but they are extremely vulnerable in this form

**Comment by Technopig1992** [comment]
Added tunnel model file "NerubianTunnel.mdx"

**Comment by YakaryBovine** [comment]
After some investigation I don't think it's going to be feasible to make a good tunneling system. We've decided to keep Deep Burrow but still remove their boats. So this ticket is now to remove everything related to the tunnel system and AQ's boats.
