### ISSUE TITLE
Stormwind - Invigoration (northshire abbey) doesn't heal

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2916]
https://discord.com/channels/553888327103807491/1230933540959686656

**Comment by Technopig1992** [comment]
hmm yes it does >.<




![Image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/cc78cfd7-3087-4535-827c-7864f20f6958)



![Image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/6f91a384-2c9f-44ee-b33a-333e9251aeb1)

**Comment by Technopig1992** [comment]
Unable to replicate the screenshot from Linaz - reopened for investigation

**Comment by YakaryBovine** [comment]
Yeah, can confirm, in normal circumstances the regen works fine.
Let's close this, and if we can get reproduction steps from the reporter we can re-open it.
