### ISSUE TITLE
Kul'tiras - Not all creeps in range of CP to be part of quest objective

### ISSUE THREAD

**Issue by vampirika** [AzerothWarsLR/WarcraftLegacies#2917]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/e9fdedfa-a55c-4af5-8092-2f576fd0eec2)

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/59606542/3ec2b4ac-50fc-42d0-8eac-ff8680b5d81f)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/da0550da8fc87a621555ac1e21e3d866dd4b2212
