### ISSUE TITLE
Tyrs Hand Creeps 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2919]
Not sure if these creeps are intentionally inside Trys hand or not - just seems strange that "The Fortified City" isn't so fortified xd and they just instantly get killed by towers when you gain control of the city. Suggest just moving them outside.

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/8dd7ba4f-4eab-4f9d-9c3c-df96d50f5a5a)

**Comment by YakaryBovine** [comment]
@Technopig1992 We shouldn't open non-bug tickets without knowing who's meant to complete them. When we do that they just sit here for weeks or months before I eventually delete them. Did you have someone in mind for who should investigate this?

**Comment by Technopig1992** [comment]
Apologies , I will assign myself and catch up with Sebas to check if placement is intended or not
