### ISSUE TITLE
Replace C'thun models and icons 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2920]
I will import the building set into the map for @SebastianTanoni to allocate accordingly

**Comment by YakaryBovine** [comment]
@Technopig1992 Good catch... Do you maybe want to talk to HerrDave about this? He doesn't follow Github so you'd be better off tagging him on Discord and explaining the problem.

**Comment by Technopig1992** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/51b25db7-ecc0-4fd8-8654-b26dbcd964c9)
Here are the building names for searching ease
