### ISSUE TITLE
Apply recently added Warsong buffs/changes to there Chaos Orc counterparts 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2935]
As it stands normal Grom has better stats than Chaos Grom. 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/bb83bf8b-8ba6-4cd5-95a1-beb58a931f75)

@vampirika

**Comment by vampirika** [comment]
Ah good point, an oversight when adjusted groms stats. Will add to next updates

**Comment by YakaryBovine** [comment]
Closed by @vampirika
