### ISSUE TITLE
Vanilla Crypt Fiend Burrow model shows as a white square

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#2962]
Just shows up as a white square: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/e2e71a6f-ef05-4ce8-ad45-c848e665be5e)

**Comment by YakaryBovine** [comment]
@SebastianTanoni This might be a good one for you to tackle as part of C'thun stage, otherwise I'll have to do it. I'm hoping it'll be something as simple as us accidentally overriding the Burrow model because obviously this isn't bugged in vanilla.

**Comment by SebastianTanoni** [comment]
When I first discovered it I checked and couldn't find any model override.

Il check again when I get homr

**Comment by YakaryBovine** [comment]
We think this is due to the new tunnel model imported for Ahn'qiraj. Will probably take some modeling knowledge to fix. 

Outcome we need is just that the Crypt Fiend burrow model shows as it does in vanilla with no workarounds needed for it.
