### ISSUE TITLE
Channeling objective is getting reset

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2967]
https://cdn.discordapp.com/attachments/1162520440388993167/1233780929973981275/Screenshot_20240427_095433_Discord.jpg?ex=662fa908&is=662e5788&hm=c006d48d9eb85c8a72db22bb1270e6582ff07fc9aff4efa05a2413b2b7a0c441&

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/0534e4ac6e5ba06e7ff85512049a593068122fda
