### ISSUE TITLE
Illidan left, but wasnt deleted from the scoreboard

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#2968]
https://cdn.discordapp.com/attachments/1162520440388993167/1233773187087466526/image0.jpg?ex=662fa1d2&is=662e5052&hm=561e4075c702466697136b792227b5f9b9f8f2875b3eb9601b84c94107552d8e&

**Comment by Technopig1992** [comment]
I believe this happens with any faction that has an alternative pick

**Comment by YakaryBovine** [comment]
Saw this happen with Scarlet Crusade too so I think it is any faction that doesn't exist at game start.
