### ISSUE TITLE
Rematerialisation Power / Argus  

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2969]
The power works on elites and units with Resistant Skin, if you are yet to summon legion  or have yet to take The Sunwell these units then become "stuck" in Argus with no reasonable way to get out. I imagine quite frustrating for the player to have limited units stuck somewhere.

**Comment by YakaryBovine** [comment]
Just removing the investigation tag as bugs have their own column in the Bug tracker Project for that.

**Comment by YakaryBovine** [comment]
Ok, so definitely a bug - the tooltip says it doesn't work on Limited units but it actually does.

**Comment by YakaryBovine** [comment]
Unassigning myself just in case anyone wants to pick these up, but I will do this if nobody else does.
