### ISSUE TITLE
If warsong leaves while Mannoroth is active the xp from the hero spreads to allies 

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#2973]

**Comment by Technopig1992** [comment]
https://discord.com/channels/1161755984759378100/1162520440388993167/1239683035067318283

**Comment by YakaryBovine** [comment]
1. Play as Warsong
2. Train Grom
3. Take control of Frostwolf and train Thrall
4. Complete the quest "The Bloodpact"
5. Get Grom to level 4
6. Kick Warsong from the game
7. Observe that Thrall is now level 20

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/edacdbaf8b29d268632103770bce6ae1842345d2
