### ISSUE TITLE
Twight light Highlands gate bugged

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#2987]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/f8628cc3-5df4-4bf2-9b45-d7eee04e61cb)

you can walk through the gate when its closed. 

In the World Editor the object used is Horizontal Gate (Dead), I tried replacing it with an Horizontal Gate (Closed) but that gate begins the game open; in short I don't know how we make gates work :)

**Comment by SebastianTanoni** [comment]
The gate is useless right now, so i removed it
