### ISSUE TITLE
 Barrage Ability (Sentinels, Archer)

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3009]
Mechanically the ability is fine.

- New Icon, currently shares an icon for a very similar but single target arrow based ability 
- New Name, currently shares the name of a vanilla Wc3 ability but does something different 

Ideally it would also be better if they did not stack but that is more personal preference for me.

**Comment by YakaryBovine** [comment]
Let's call this one a bug, you've identified that it doesn't meet the ability guidelines!
