### ISSUE TITLE
Cityscape (night?) ambiance in the middle of the sea

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#301]
![image](https://user-images.githubusercontent.com/47048283/201682613-9ccf4910-c927-43ce-a55a-542a4efd2e46.png)

**Comment by SebastianTanoni** [comment]
Its actually global, theres a city scape ambiance everywhere

**Comment by YakaryBovine** [comment]
Turns out we just need to disable the map's default ambiance like the JASS version does: 
https://cdn.discordapp.com/attachments/755524123375173677/1041813499233443900/image.png

I also suggest re-confirming whether or not AmbianceSetup.cs works before closing this.
