### ISSUE TITLE
Create Amphibian ability and code

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#302]
Makes the unit that has this passive receive 50% extra damage when in water

**Comment by YakaryBovine** [comment]
Done my part: https://github.com/AzerothWarsLR/WarcraftLegacies/commit/e97512ce1cfea92ae6cd3b6a6cd764cf34182090
Follow-up ticket here: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/375
