### ISSUE TITLE
Guardian of Trisfal - does not fail when Violet Citadel is destroyed 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3024]
https://media.discordapp.net/attachments/1239267159176253582/1239267159926898930/image.png?ex=66424cfb&is=6640fb7b&hm=f8b8b13285fd902a7584eb8925b3f6caf15d3dfc904676c8cb13a1cac681240a&=&format=webp&quality=lossless&width=960&height=748

**Comment by YakaryBovine** [comment]
Unassigning myself just in case anyone wants to pick these up, but I will do this if nobody else does.

**Comment by YakaryBovine** [comment]
So if you look at the quest objectives... The "false" highlighted here means that the objective doesn't fail when the capital is lost. So probably just need to change that to true and it will work as apparently intended.
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/6eb4aabb-1c19-4415-8446-752e37ac4b3f)

**Comment by YakaryBovine** [comment]
BTW @Technopig1992 the link in the description is dead or I don't have access to it. I'd recommend uploading images to Github instead of linking to Discord

**Comment by YakaryBovine** [comment]
Actually... Dalaran isn't capturable so probably this should be something like ObjectiveLegendAlive (assuming that exists, will need to create it otherwise).
