### ISSUE TITLE
Sunfury's Void Reaver doesn't have the Inventory (Hero) ability

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3026]
But is trained from the altar

**Comment by YakaryBovine** [comment]
What does "isn't demi-hero" mean? Not limited to 1? Doesn't have Resistant Skin?

**Comment by Technopig1992** [comment]
Good point. I think the only thing separating Demi's from limited units  is the ability to use items and being limited to 1 however this Demi cant use items so is it not just a limited unit trained in the wrong place.

**Comment by YakaryBovine** [comment]
> Good point. I think the only thing separating Demi's from limited units is the ability to use items and being limited to 1 however this Demi cant use items so is it not just a limited unit trained in the wrong place.

Sweet, updated title accordingly!
