### ISSUE TITLE
Destroyed Horizontal Elven Gate erroneously has the Open Gate ability

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#3029]

**Comment by linaz2009** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/fd18bc3a-45d6-48b4-9ec7-03b49bbc506e)

**Comment by linaz2009** [comment]
@YakaryBovine not really fixed

**Comment by SebastianTanoni** [comment]
? it doesnt have any requirements?

**Comment by linaz2009** [comment]
it's destroyed gate, shouldn't have "open gate" ability at all

**Comment by YakaryBovine** [comment]
> it's destroyed gate, shouldn't have "open gate" ability at all

Good catch, thanks for reporting! Will re-open.
