### ISSUE TITLE
More reports on the Legion portal bug

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#3044]
https://imgur.com/a/Lo9mYIq

If you open the portal to nr a 2nd time the portal wont be linked to the nr one
replication:

1. 1st portal open to nr is fine
2. if you try to open the portal a 2nd time (or more infact since i tried) it will open the portals to nr and argus but they are not linked

"i do not know if they link to other portals. i have seen in the past people saying that sometimes the portals link to the kul tiras ship but in this specific game i played neither portal lead anywhere"

**Comment by YakaryBovine** [comment]
Merging with this ticket as we think it describes the same issue: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2243
