### ISSUE TITLE
Stormwind Conjuror summon has the Summon Water Elemental buff

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3046]
named Water Elemental in game should be Scorpion 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/42575334-6060-437f-ad3b-93d64ed9f0be)

**Comment by YakaryBovine** [comment]
@Technopig1992 If it's OK with you I'll take this one. Better to automate this because we have many, many instances of getting this wrong.

**Comment by YakaryBovine** [comment]
> @Technopig1992 If it's OK with you I'll take this one. Better to automate this because we have many, many instances of getting this wrong.

Scratch this, sorry. I'm having some issues with Ability automation at the moment so in the mean-time we can fix this as a one-off via object editor.
