### ISSUE TITLE
The Slumbering King 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3047]
Completed at a point in the game that should be impossible. 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/30e1f2ce-484c-40d5-b9b2-74328e3cd03e)
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/2b5aeae7-ec12-493a-89a4-9ffe15e59c96)
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/103082ea-1e80-4996-a6da-b5630b9e2dc6)

**Comment by YakaryBovine** [comment]
@SebastianTanoni Techno mentioned you might have the replay for this one? Could you upload it to this ticket?

**Comment by Technopig1992** [comment]
Ty ! Sent from my iPhoneOn 22 May 2024, at 16:42, linaz2009 ***@***.***> wrote:﻿
https://dropmefiles.com/cZ1XQ

**Comment by YakaryBovine** [comment]
> https://dropmefiles.com/cZ1XQ

Beautiful, thank you

**Comment by YakaryBovine** [comment]
Sebas to watch the replay, then hand it back to me with any findings for a fix.

**Comment by YakaryBovine** [comment]
I watched the replay and couldn't find a single Fel Horde unit entering Northrend, so I've modified the quest to:
 - Indicate in quest text the name of the unit entering Northrend
 - Ping the unit entering Northrend
This should make it really clear what's happening next time it comes up.

**Comment by linaz2009** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/57cf3efb-8991-46be-92b1-2a93cca02e66)
no ping/indicated unit, playing on 3.14.21

**Comment by linaz2009** [comment]
https://dropmefiles.com/63uxS

**Comment by YakaryBovine** [comment]
> ![image](https://private-user-images.githubusercontent.com/119281194/335812018-57cf3efb-8991-46be-92b1-2a93cca02e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzkzNTYsIm5iZiI6MTcxNzI3OTA1NiwicGF0aCI6Ii8xMTkyODExOTQvMzM1ODEyMDE4LTU3Y2YzZWZiLTg5OTEtNDZiZS05MmIxLTJhOTNjY2EwMmU2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQyMTU3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjFkODRhYTlmNTFlYWJjMzY3YWFjMWQxYmYyOTljYjdhMDQxOWYxMjFiOGVmZWRmNDI4NTFkNGQ0ZDc1N2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cHZIuP_4OLR2615ieoVLkeIGdVOCRIBdglq7GYiATkY) no ping/indicated unit, playing on 3.14.21

Thanks, looks like the release of 3.14.21 was missing a lot of the changes we made. 3.14.22 should now contain this change.
