### ISSUE TITLE
The "Turn 6 has passed" research did not complete for player while the turn timer indicated that it was partway through turn 7

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3057]
![Uploading image.png…]()

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/3c3fe77f-d23c-430e-aa9e-7d8443c250f0)

Reported reproduction steps:

- Start the map in Single Player 
- Select Scourge
- Observe Flight and Navigation are still locked after turn 6 has passed

**Comment by YakaryBovine** [comment]
I followed the indicated reproduction steps but the bug did not occur for me on singleplayer using 3.14.21: 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/8995690/2f993675-967b-42b2-8c6b-5a2cf345fd39)

Also @Technopig1992 the bug isn't pictured in the screenshot, I just see a Frost Wyrm being trained at turn 9. Do you have another image?

**Comment by YakaryBovine** [comment]
I think to progress this one we're going to need a replay!

**Comment by Technopig1992** [comment]
sadly no replay was available but ill ask if he can replicate as he seemed to think he did it multiple times. hmm odd first image didn't upload 

![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/1351946e-8eec-49b3-9bd1-b6c281c8b74b)
 
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/80bd95e2-01b2-4d34-8a45-f73b2136ff1a)

**Comment by Technopig1992** [comment]
Has not been reported since nor have I been able to replicate. Original poster has confirmed it was in Single Player, thinking it might just be them pressing escape to skip the cinematic and started the timer off. Possibly okay to close?

**Comment by YakaryBovine** [comment]
Yeah, if we're not going to get a replay from them it's impossible to solve anyway so let's close.
