### ISSUE TITLE
Make the income system able to apply to unit

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#307]
Want to give 2 units a passive that reduce your income slightly!

**Comment by YakaryBovine** [comment]
The relevant class here is ProvidesIncome.cs. Right now it will only work for structures (I think). Allow it to work for trained units too.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/1d4bfb0925d0997fd24b02fa289ebe63a18acc8e. @SebastianTanoni you should be able to configure the units you wanted.

**Comment by SebastianTanoni** [comment]
To-do: configuire the units
