### ISSUE TITLE
Incorrect damage type on some custom spells 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3088]
The damage type for some custom abilities are coded incorrectly as DAMAGE_TYPE_MAGIC (magic damage) that should be DAMAGE_TYPE_NORMAL (spell damage), 

Defensive Orbs (Anesterian) 
Solar Judement (Arthas)
Warglaives Of Azzinoth

**Comment by YakaryBovine** [comment]
I will do this if nobody else does, but technically anyone could. Just do a good search for DAMAGE_TYPE_MAGIC and see if it's a spell. If it is, replace it with DAMAGE_TYPE_NORMAL. TBH I doubt anything is actually meant to be DAMAGE_TYPE_MAGIC.

**Comment by YakaryBovine** [comment]
@Technopig1992 Just had a quick look and it's actually only DefensiveOrbMissile.cs that is wrong. Remember that damage type can be almost anything but is usually DAMAGE_TYPE_MAGIC. For spells, though, _attack type_ must be ATTACK_TYPE_NORMAL.

Reference: https://www.hiveworkshop.com/threads/spell-ability-damage-types-and-what-they-mean.316271/

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/f3b166b21a8a77338185e88acb933895eecfbc7f
