### ISSUE TITLE
Cenarius movement speed reduction aura values are wildly too high

### ISSUE THREAD

**Issue by Ripzss** [AzerothWarsLR/WarcraftLegacies#3095]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/105180704/b66eb4c2-90ff-42fc-8f94-ad17c4c9f590)

**Comment by Ripzss** [comment]
Movespeed got changed instead of attack speed
resulting in lvl 3 having a 90% movement speed reduction

**Comment by Technopig1992** [comment]
Closed with .26 hotfix

**Comment by YakaryBovine** [comment]
> Closed with .26 hotfix

Nope! It's closed when a Pull Request has been accepted into `main`.

**Comment by Technopig1992** [comment]
> > Closed with .26 hotfix
> 
> Nope! It's closed when a Pull Request has been accepted into `main`.

oops!
