### ISSUE TITLE
Legion Rematerialisation power is not removed when the player uses the -obs command 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3103]

**Comment by Technopig1992** [comment]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/127978232/56374b28-2ff6-42c3-bee1-841eb48264d4)

**Comment by YakaryBovine** [comment]
Closed by [Defeating a player removes their Faction before killing and removing their units](https://github.com/AzerothWarsLR/WarcraftLegacies/commit/71b42204d8ee29fd9af07dee15c93d625136775b)
