### ISSUE TITLE
Goblin trader can complete the slumbering quest VERY early

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#3107]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/86e15046-33fc-44f1-b849-dcb1c823b208)
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/c0e33313-eccf-4200-8a65-7a3f9e159d94)

**Comment by YakaryBovine** [comment]
I think the best fix to this is to just make naval units not count for the quest. Only really counts as encroaching if you land anyway.

**Comment by vampirika** [comment]
#2932 would have addressed this. If we consider this a bug now I can have a go at doing it (in main).

**Comment by YakaryBovine** [comment]
> #2932 would have addressed this. If we consider this a bug now I can have a go at doing it (in main).

Good catch, I'll close this one.
Yeah I think we can call it a bug - at the very least it's breaking the design intent of the objective.
