### ISSUE TITLE
Scourge can send Sapphiron to NA goldmines before they can defend themselves

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#3114]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/43792e40-d8b9-40e4-b96c-2ddf323981af)

**Comment by Ripzss** [comment]
Quest that makes Sapphiron to spawn only requires players to kill Sapphiron  and control Kel'thuzad.

Solution to this would be to add a new objectiveTime(x) to turn requirement to when players can unlock flight or have flight researched to complete the quest.

**Comment by YakaryBovine** [comment]
> Quest that makes Sapphiron to spawn only requires players to kill Sapphiron and control Kel'thuzad.
> 
> Solution to this would be to add a new objectiveTime(x) to turn requirement to when players can unlock flight or have flight researched to complete the quest.

Right makes sense.
Ok let's go with the solution of the quest requiring Flight. Makes sense that a quest that gives you a flying unit should require Flight.

**Comment by vampirika** [comment]
I've picked this up #3116

**Comment by YakaryBovine** [comment]
Closed by #3116
