### ISSUE TITLE
after someone leave book quest is failed

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#3128]
![image](https://github.com/AzerothWarsLR/WarcraftLegacies/assets/119281194/24ad57b3-e354-4fc8-ab0b-2409fd944713)

**Comment by linaz2009** [comment]
![image](https://github.com/user-attachments/assets/87c32ecd-661a-480e-8a47-58e4b8355f6b)
might be related might be not, no leaver this time

**Comment by YakaryBovine** [comment]
Thankyou for the report.

Fixed in https://github.com/AzerothWarsLR/WarcraftLegacies/commit/2928bdc49911df7621c175717cf3db80c22acf26
Should probably be released as a minor version before Old Gods patch.
