### ISSUE TITLE
New passive hero ability: Blood absorption

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#313]
When units get hurt around the hero, he recuperate a fraction of the damage in mana

its for the new hero Gorfax, who is a melee healer themed hero (around blood)

**Comment by YakaryBovine** [comment]
@SebastianTanoni I misread this - I thought it just needed to give mana based on the damage Gorfax does, rather than damage based on any unit around him. This is a lot more complicated (though still doable) so it'll have to wait until 2.1 or get simplified.

**Comment by SebastianTanoni** [comment]
Just change it to what you said, how much damage he does 100% conversion

**Comment by SebastianTanoni** [comment]
@YakaryBovine

**Comment by SebastianTanoni** [comment]
The numbers would be 100/120/150/200

**Comment by SebastianTanoni** [comment]
% of damage

**Comment by YakaryBovine** [comment]
I can do that.
