### ISSUE TITLE
War Stomp Animation when using the Stomp spell?

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#3132]
When using the Stomp spell in the code, even though the animation i specified is not the war stomp one, the war stomp animation plays in game

![image](https://github.com/user-attachments/assets/d7ce2f7b-ed9b-4cb7-b349-7a654af46c47)

**Comment by YakaryBovine** [comment]
The issue is in Stomp.cs:

`
    /// <inheritdoc />
    public override void OnCast(unit caster, unit target, Point targetPoint)
    {
      EffectSystem.Add(AddSpecialEffect(SpecialEffect, GetUnitX(caster), GetUnitY(caster)));
      
      foreach (var enumUnit in CreateGroup()
                 .EnumUnitsInRange(new Point(GetUnitX(caster), GetUnitY(caster)), Radius)
                 .EmptyToList())
      {
        if (!CastFilters.IsTargetEnemyAndAlive(caster, enumUnit)) continue;
        DamageUnit(caster, enumUnit);
        StunUnit(caster, enumUnit);
      }
      DestroyEffect(AddSpecialEffect(@"Abilities\\Spells\\Orc\\Warstomp\\WarStompCaster.mdl", GetUnitX(caster),
        GetUnitY(caster)));
    }
`
As you can see both `SpecialEffect` AND `Abilities\\Spells\\Orc\\Warstomp\\WarStompCaster.mdl` are created. I have to assume the latter was a mistake?
