### ISSUE TITLE
Add the 6% health damage on the mass unholy armor spell i made

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#314]
So when unholy armor is cast, the code needs to deal 6% of the target health as damage. But i dont know how to insert that in the mass spell

**Comment by YakaryBovine** [comment]
@SebastianTanoni I'll show you how to do this one, it's really easy to do with just configuration. Let me know when you're free.

**Comment by YakaryBovine** [comment]
Appears to be a little buggy so I'll handle it.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/ab9bb0e6e777b32720a30d7a53fff7f50030575e.
