### ISSUE TITLE
Destroyer of Worlds Quest- Completed but no reward 

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3174]
![image](https://github.com/user-attachments/assets/6e7e7f80-c3a9-4f56-801d-d14fbf2f8413)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/32c0932920d0c644cb23e3782c06445bab099b3c
