### ISSUE TITLE
Units transformed by Worgen Blood Shamans join the player not the creeps

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#318]
![image](https://user-images.githubusercontent.com/93258020/201993438-a4ff5053-772c-49e1-9b9c-af6bc570faf2.png)

**Comment by YakaryBovine** [comment]
Hi @TracyTheBoy, I've pre-emptively assigned this to you since it's Gilneas related. If you'd prefer not to do it please feel free to unassign.

**Comment by YakaryBovine** [comment]
Sebas says we can just delete this spell.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/c3b55efbd668b8748e97182f08e6386846a4fba0.
