### ISSUE TITLE
Creeps not waking up during daytime

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#319]
![image](https://user-images.githubusercontent.com/93258020/201993919-8b81a8d6-5c99-4ad3-a8e7-0f808af593a4.png)

**Comment by YakaryBovine** [comment]
This is an interesting one. @SebastianTanoni can you confirm it's a bug?

**Comment by SebastianTanoni** [comment]
It is a bug!
