### ISSUE TITLE
Kul Tiras , Flagship removed and no teleport if STV Expedition is failed due to elapsed time

### ISSUE THREAD

**Issue by Technopig1992** [AzerothWarsLR/WarcraftLegacies#3192]

**Comment by YakaryBovine** [comment]
Not a bug; this was intentionally changed to work this way and has done so since 2022.
It could be changed again, but it would be a feature change.

**Comment by Technopig1992** [comment]
No problem , there was a reason I added it as a bug, I’ll have to go back and double check . ( I think you can still research stv expedition  even after failing the quest or something similar and it’s not clear that the flagship will be removed if you fail the quest, something like that Sent from my iPhoneOn 10 Nov 2024, at 01:00, Zakary Boven ***@***.***> wrote:﻿
Not a bug; this was intentionally changed to work this way and has done so since 2022.
It could be changed again, but it would be a feature change.
