### ISSUE TITLE
Dragon Level up system

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#322]
whelp->Drake-> Ancient Dragon

**Comment by YakaryBovine** [comment]
Probably need more details on this, I didn't take it all in :D

**Comment by SebastianTanoni** [comment]
Details:

You have 6 available dragon slots, those can be either of  Whelps, Drakes or Ancient Dragons.

When a Whelp survives in combat long enough (exact game mechanic to be determined) it upgrades to a Drake.

Once a drake survives long enough in combat, it upgrades to an Ancient Dragon

Very important, the unit limit is shared. So if you are limited to 6 Whelps. Once your whelps evolve to drakes and dragons, you do not gain more room to build new whelp. Only a dragon dying means you free a slot

**Comment by SebastianTanoni** [comment]
Here are the objects for the 3 dragons:

Whelp: N0CQ

Drake: N0DB

Ancient Dragon: N0CP

**Comment by YakaryBovine** [comment]
Dragonmaw aren't around at the moment so we probably need to revisit this if/when they're re-implemented.
