### ISSUE TITLE
Enslaved Dragon 2 (Nice to have)

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#324]
Each new color of dragon augments the limit of dragons, to incentivize players to go and get the different colored dragons

**Comment by SebastianTanoni** [comment]
So you start with only 6 possible whelps. Once you lvl them to ancient dragons, you cannot build anymore. 

If you then unlock a new color, you get 6 more dragons "slots"

**Comment by YakaryBovine** [comment]
Dragonmaw aren't around at the moment so we probably need to revisit this if/when they're re-implemented.
