### ISSUE TITLE
Nether Exit is not mentioned anywhere??

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#328]
![image](https://user-images.githubusercontent.com/47048283/202192257-0228b81e-5ca9-4e9c-8446-fd5017315e0e.png)

When the legion is summoned, the appearing portal destination should be set to this region

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this

**Comment by SavanticIO** [comment]
I don't think this is an issue. Legion summoning works fine. Destination is just set to the location of that preplaced portal unit, no need for the region.

**Comment by YakaryBovine** [comment]
Sweet, that actually makes sense. Thanks @SavanticIO.
