### ISSUE TITLE
Completing awakening of Stormrage doesnt not grant the world tree

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#330]
![image](https://user-images.githubusercontent.com/47048283/202206923-f9c3c2c8-f830-4a43-9a9f-b2a81c5b02ab.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/0181e5c0b3b178fb719032dc312e9f188a54a723.
