### ISSUE TITLE
Spirit of Ashenvale quest is missing a component

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#331]
Current

![image](https://user-images.githubusercontent.com/47048283/202207082-188a8373-4829-49c6-aa2b-3db7ff96af83.png)

![image](https://user-images.githubusercontent.com/47048283/202207204-d6d1502b-8575-485a-9479-e6415b0d385a.png)

missing:

![image](https://user-images.githubusercontent.com/47048283/202205629-846a4234-86f0-4ce5-a919-6ad5625da098.png)

![image](https://user-images.githubusercontent.com/47048283/202205880-d52e58d7-02c0-4cc1-be7e-86573cde1bb2.png)

![image](https://user-images.githubusercontent.com/47048283/202206266-cd1f78e3-ef27-4dea-b228-418b8a51f1e9.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/542b9281060a5dad75b4629de2d94e7282c314df.
