### ISSUE TITLE
Dreanei Power: Crystal Allignement

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#341]
For each Arcane Well (house) that is in contact with a building, that building will produce units faster and reimbource a percentage of their cost once they are trained

**Comment by YakaryBovine** [comment]
Couple of discussed issues with this one:
* It would discourage players from training units anywhere they don't have a full set of Arcane Wells.
* Producing units faster is impossible as far as I know.

Arcane Wells having some of positive effect on buildings is a good idea though, and worth retaining in a document somewhere.
