### ISSUE TITLE
Forsaken/Cult Power: Unturned Graves

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#343]
When corpses are generated around their control point, the control point stores the corpse to a maximum of X.

When that control point is attacked, it will automatically revive the units stored inside it.

**Comment by SebastianTanoni** [comment]
corpses generation could be via anything dying, meat carts, or forsaken graves

**Comment by YakaryBovine** [comment]
We'll probably want to represent the corpse count with mana.
The units reanimated will come from a pool of units that make sense for the Forsaken, e.g. Forsaken units, Quel'thalas rangers, human footmen.

**Comment by SebastianTanoni** [comment]
Let's make this a scourge power

**Comment by YakaryBovine** [comment]
No specific plans to do this one and I don't think anyone else knows how to make Powers so I'll close it. Could be moved into an ideas document.
