### ISSUE TITLE
Factions without power

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#348]
- [ ] Dalaran
- [ ] Dragonmaw
- [ ] Kul'tiras
- [ ] Militia
- [ ] Zandalar
- [ ] Illidan

**Comment by SebastianTanoni** [comment]
Illidan power could be amphibian?

**Comment by TracyTheBoy** [comment]
Do you want us to brainstorm powers for these factions?
