### ISSUE TITLE
I killed Morghor but it did not register the quest objective

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#352]
![image](https://user-images.githubusercontent.com/47048283/202268585-51e55cd1-064d-456d-892c-00a095815534.png)

I must have messed up somewhere but i cant find where

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/pull/367.
