### ISSUE TITLE
Gilneas: Tess Mirror Images drop their items when they disappear

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#358]

**Comment by YakaryBovine** [comment]
Haha that makes sense. Confirmed.
Note that this probably applies to _all_ mirror images, and it'll be because something is calling `UnitExtensions.DropAllItems` that shouldn't.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/4c8ca8d82f7e4f6764e1e4670fa125f2179027bb.
