### ISSUE TITLE
Summon legion timer doesn't look right

### ISSUE THREAD

**Issue by SavanticIO** [AzerothWarsLR/WarcraftLegacies#363]
![image](https://user-images.githubusercontent.com/2250380/202514941-41e00219-ffe5-4f80-a4cd-2c279bcc439e.png)

**Comment by TracyTheBoy** [comment]
I tested this as Legion and it looked normal to me.

**Comment by YakaryBovine** [comment]
So, clearly this issue exists but I can't replicate it either. I'm going to move it to the 2.1 Milestone and hope that once we release we can narrow it down with bug reports.

**Comment by SavanticIO** [comment]
I was able to reproduce it again. Steps for me as follows;
1. Start as legion
2. do the commands -vision on -god on - tele on
3. Train a hero
4. Tele them to book of Medivh location
5. Tele away somewhere
6. use book to summon legion

**Comment by SavanticIO** [comment]
I guess there must be. Could be my ui settings, im on an ultra wide monitor.

**Comment by YakaryBovine** [comment]
From research I think this is just a native WC3 issue on wider monitors.
