### ISSUE TITLE
Configure TakesExtraDamageOnWater PassiveAbility

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#375]
I have implemented the TakesExtraDamageOnWater PassiveAbility, and made some example configuration at IllidariSpellSetup.cs. Configure that file how you like, ensuring that:
* All amphibious units are included
* The ability ID is set to a passive with a proper name and icon

**Comment by SebastianTanoni** [comment]
To DO: Change the Ability ID
