### ISSUE TITLE
Teams werent removed for being empty?

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#380]
![team didnt disapear](https://user-images.githubusercontent.com/47048283/202801267-d35b1e04-59b4-427b-9991-e5581c3d48ad.PNG)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/4ce8e2717dd1e37068bd3bc032df699a84e3865b.
