### ISSUE TITLE
Desync at turn 4

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#382]
![Desync at turn 4](https://user-images.githubusercontent.com/47048283/202801444-c0b6e8a7-6f55-4f79-a91e-7ceb9f625e0a.PNG)

Apparently he desynced when he started fighting at the tower near Thandol Bridge

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/202801799-5ef59603-0bdc-485b-a5c6-048d36fcfca6.png)

He was fighting over here when it happened

**Comment by YakaryBovine** [comment]
Fixed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/715fb9148859175bd9585ddd450fd0c3500f5f21.
