### ISSUE TITLE
If you do not vote in the open alliance vote, you get stuck in the window with no way to leave or play

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#390]
Thats the bug you encountered when we tested last time, the mystery window you couldnt close

**Comment by YakaryBovine** [comment]
Nice find!

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/a19da2b6703c017fcf68ff68c141e3a8c7e31abd.
