### ISSUE TITLE
Two death messages are displayed when Mor'ghor dies

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#392]
![image](https://user-images.githubusercontent.com/47048283/202856513-5fe91ad4-3d81-43a8-8181-b3fad07141c0.png)

**Comment by YakaryBovine** [comment]
@SebastianTanoni I can fix this, but I also don't think you have this set up right. Does Mor'ghor even count as a Legend? Does he need a global death message? He seems like a normal creep to me, like the Sea Witch. Why not just remove his death message?

**Comment by SebastianTanoni** [comment]
> @SebastianTanoni I can fix this, but I also don't think you have this set up right. Does Mor'ghor even count as a Legend? Does he need a global death message? He seems like a normal creep to me, like the Sea Witch. Why not just remove his death message?

Oh yeah, il do that!
