### ISSUE TITLE
Dragonmaw Portal to Orgrimmar appears when Dragonmaw Port base is acquired (it shouldn't)

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#393]
![image](https://user-images.githubusercontent.com/47048283/202857486-39b824b1-9608-4493-9f5f-3c9df3b96b8b.png)

**Comment by YakaryBovine** [comment]
@SebastianTanoni Did you want me to look into this or is this an issue with the quest config?

**Comment by SebastianTanoni** [comment]
I would like you to look at it, since it's not "active" you cant go through, it's just not hidden

**Comment by YakaryBovine** [comment]
Will do!

**Comment by YakaryBovine** [comment]
@SebastianTanoni Can you give me replication steps? For me it starts invisible: 
![image](https://user-images.githubusercontent.com/8995690/202889049-50f64dca-0be7-4f2c-96a8-0499afbcf8d4.png)

And appears when I complete The Reunification of the Horde:
![image](https://user-images.githubusercontent.com/8995690/202889059-b867c84c-bdab-407e-9efc-58f6d3c405f1.png)

**Comment by SebastianTanoni** [comment]
wierd, it definately appeared before its time, for now lets close it, since its not an egrigious bug. But if i have a more concrete way to reproduce it, we can revisit this

**Comment by SebastianTanoni** [comment]
I found out why. WHen you unlock the Dragonmaw Port base, it makes the protal appear, and also appear while being vulnerable and owned by the dragonmaw player

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/b5be32d2d05b5760ab2bb764b60031e71488c2cc.
