### ISSUE TITLE
All open gates should be ordered to open at game start, so they are not visually closed

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#397]

**Comment by YakaryBovine** [comment]
@SebastianTanoni 
![image](https://user-images.githubusercontent.com/8995690/202874238-dc8ac739-fe73-46e5-a3b7-cdb0c1ea0d59.png)
Looks fine to me. What's a specific gate that's not showing as open?

**Comment by SebastianTanoni** [comment]
its working fine now when i tested, so lets assume it works, and if i see it again, we can revisit this
