### ISSUE TITLE
Configure Blood Absorption

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#407]
Correctly configure the `RestoreManaFromDamage` ability in `DragonmawSpellSetup`. An example has been provided for you.

**Comment by SebastianTanoni** [comment]
@YakaryBovine What does the f means? 0.8f? is that 8% 80% ?

**Comment by YakaryBovine** [comment]
@SebastianTanoni When you type a decimal number such as 1.05, the compiler will by default interpret it as a `double`. `double`s are more precise than `float`s. But we can only use `float`s. Thus, we have to put the `f` to force the compiler to treat it as a `float`. It doesn't do it for us automatically because it doesn't want us to accidentally lose number precision.
Short rule of thumb: just always put an `f` after the number if it's a decimal.

And to figure out what the 0.8 means, hover over the `ManaPerDamage` property. It should tell you explicitly!
