### ISSUE TITLE
Make the Artifact menu much wider and push it down to ensure it doesn't clash with the game timer

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#413]
Old vJASS version looks cooler because it's wider:
https://cdn.discordapp.com/attachments/834150068059242527/1043826508193611876/image.png

New version:
https://cdn.discordapp.com/attachments/834150068059242527/1043827130225668176/image.png

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/adfcace65f2fc59e0cd0100a887d46a0987c34c4

**Comment by TracyTheBoy** [comment]
I know this is closed but I just wanted to note in case you overlooked it that the old version has 5 items per row instead of 4 like the new version.
