### ISSUE TITLE
QuestGrimBatol failed to due to ObjectiveOnExpire after the quest was already complete

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#424]

**Comment by YakaryBovine** [comment]
@SebastianTanoni 480 seconds is only 8 minutes, so this quest fails at 8 minutes. Is that what you intended?

**Comment by SebastianTanoni** [comment]
Yes! But in this case, both quests were completed before turn 8

**Comment by YakaryBovine** [comment]
Cool, I'll take it then since it's probably a core quest issue.

**Comment by YakaryBovine** [comment]
@SebastianTanoni Not a system bug. I think you just need to delete `TwilightQuestSetup.cs`. There are currently two copies of `QuestGrimBatol`, and the Twilight one is failing, causing the base to go hostile.
