### ISSUE TITLE
Multiboard incorrectly shows Frostwolf and Dragonmaw as being part of the Alliance in some circumstance

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#426]
![image](https://user-images.githubusercontent.com/47048283/202926352-ca11f60e-e0fa-4125-b888-420adb779390.png)

**Comment by YakaryBovine** [comment]
Does look like a bug. Let's icebox this until we have clear reproduction steps. Hopefully it's a fringe issue.

**Comment by SebastianTanoni** [comment]
Just to be clear, horde was still enemy with alliance at that point

**Comment by YakaryBovine** [comment]
Probably fixed incidentally.
