### ISSUE TITLE
Outland Portals don't teleport you from Eastern Kingdoms to Outland

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#457]
And possibly other issues.

**Comment by SebastianTanoni** [comment]
Portal should open at turn 10

**Comment by YakaryBovine** [comment]
Looks like this quest from the live version just flat out isn't implemented: https://github.com/AzerothWarsLR/AzerothWarsLR/blob/master/jass/Quests/Fel%20Horde/QuestDarkPortalOpen.j

**Comment by SebastianTanoni** [comment]
Ah yes! there it is, i vaguely remembered i added that quest :)

**Comment by TracyTheBoy** [comment]
I'll take this
