### ISSUE TITLE
ObjectiveControlPoint doesn't reflect Team changes due to new Team/Player system

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#46]
If a Faction has a Quest Objective to capture a particular Control Point, and that Faction joins the Team that controls that Control Point, the Objective should be completed. Right now that doesn't happen. Here are all the cases to cover:
 * Complete the objective when joining a Team that has the Control Point
 * Complete the objective when a Faction joins _your_ Team and they have the Control Point
 * Incomplete the objective when leaving a Team that has the Control Point
 
 This issue may also apply to ObjectiveControlLegend.

**Comment by YakaryBovine** [comment]
I modified the Team cheat. It now lets you set any Faction's Team. The syntax is `-team x y` where `x` is the name of a Faction and `y` is the name of a Team. For example you can do `-team Scourge Horde` to change the Scourge's team to Horde.

**Comment by SavanticIO** [comment]
That's great thanks. I'll start taking a look today.
