### ISSUE TITLE
Batrider's Acid Bomb is applying the incorrect debuff

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#480]
![image](https://user-images.githubusercontent.com/8995690/203520038-8648d00c-8acc-4d67-948f-f68a915dd58a.png)
![image](https://user-images.githubusercontent.com/8995690/203520011-7ab97e22-5cb8-49ff-a60e-e1d43c92fdc7.png)

**Comment by HerrDave** [comment]
Fixed

Both the Batrider and Hero versions now apply the correct Debuff
