### ISSUE TITLE
Stonemaul base instantly turned hostile after Frostwolf completed The Chieftain's Challenge

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#481]
![image](https://user-images.githubusercontent.com/8995690/203521769-e9b52bff-e4ba-4e10-b3da-399b582268cd.png)
![image](https://user-images.githubusercontent.com/8995690/203521602-cadad814-1f92-4a2c-8c1c-c0eb86cc3a36.png)

This is because the quest goal conflicts with that of Ruins of Stonemaul for Dragonmaw.
![image](https://user-images.githubusercontent.com/8995690/203521841-1365ce43-ef7a-4578-9433-5f516a540b05.png)
![image](https://user-images.githubusercontent.com/8995690/203521853-709062c8-c6b1-45d6-b98d-752a53d6ee01.png)

**Comment by SebastianTanoni** [comment]
todo: change kill objective to Is dead

**Comment by SavanticIO** [comment]
@YakaryBovine I'll take this one
