### ISSUE TITLE
Renewal visual effect doesn't appear on Draenei units

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#482]
![image](https://user-images.githubusercontent.com/8995690/203522431-817fed0c-e7bf-4111-a2cc-200508765806.png)
Might be an issue for all attachments on Draenei.

**Comment by HerrDave** [comment]
Confound these blasted space goats, man

Gone are the days of the shadowmeld using, hand-scythe wielding potato faced master-race :(

**Comment by HerrDave** [comment]
Fixed
