### ISSUE TITLE
Picking Scarlet Path should fail Argent Path, and vice versa

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#494]

**Comment by YakaryBovine** [comment]
@SebastianTanoni Is this how it works in the vJASS version?

**Comment by SebastianTanoni** [comment]
Im fairly certain

**Comment by YakaryBovine** [comment]
I don't see anything in there that could be doing that so I'll icebox this one for now.

**Comment by SebastianTanoni** [comment]
> I don't see anything in there that could be doing that so I'll icebox this one for now.

No issue, i think when we do 2.1, while you work on forsaken, il rework scarlet and how they work!
