### ISSUE TITLE
Zandalar and Kultiras second chances are not activating properly

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#498]
They do not lose their former holdings

**Comment by TracyTheBoy** [comment]
Kul'Tiras worked properly for me when I killed Boralus as Kul'Tiras

**Comment by SebastianTanoni** [comment]
> Kul'Tiras worked properly for me when I killed Boralus as Kul'Tiras

That means: you lost control of everything you owned prior, you gained the ship moving towards south shore, your heroes revived into the ship and you gained control of all the units inside the ship?

**Comment by TracyTheBoy** [comment]
Yes that's exactly what happened.

**Comment by TracyTheBoy** [comment]
Working on fixing the Zandalar side of this
