### ISSUE TITLE
Scholomance Portal is open from the start

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#506]
![image](https://user-images.githubusercontent.com/8995690/203765401-d6743897-f0bf-4bf6-ac6a-b13cd6034c6e.png)

**Comment by SavanticIO** [comment]
I think this was done as part of fixing #409

In maps/source.w3x/war3map.lua

u = BlzCreateUnitWithSkin(p, FourCC("n04B"), -21056.0, 17536.0, 88.511, FourCC("n04B"))
WaygateSetDestination(u, GetRectCenterX(gg_rct_Scholomance_Entrance), GetRectCenterY(gg_rct_Scholomance_Entrance))
WaygateActivate(u, true)

**Comment by YakaryBovine** [comment]
Haha yep. I got a bit overzealous with making waygates.

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/28cd138295a0366e38b02d92d6497ece473531be.
