### ISSUE TITLE
Scarlet Units are invulnerable after being unlocked

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#516]
![image](https://user-images.githubusercontent.com/47048283/203806042-f1ba84cf-ab2b-4a49-89e4-d00859d9e3b4.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/6e9c27d06813a5a13a5ef5e26d61831a3be88131.
