### ISSUE TITLE
No goblin teleporter

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#522]

**Comment by YakaryBovine** [comment]
![image](https://user-images.githubusercontent.com/8995690/204069754-f4f1f061-18d6-4a41-bc88-6d258b9eff3c.png)
@SebastianTanoni Working OK for me in testing. Is it still an issue for you? I'm wondering if something weird is happening when we publish. Or maybe when we play multiplayer.

**Comment by TracyTheBoy** [comment]
Can be marked as completed.
17b8467 solved this.
