### ISSUE TITLE
Goblin zeppelin dont appear

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#524]

**Comment by SebastianTanoni** [comment]
When they are trained, gobelin zeppelin dissapear immediatly

**Comment by YakaryBovine** [comment]
![image](https://user-images.githubusercontent.com/8995690/204069658-b6a0063d-d10a-48da-ba34-36561b48b236.png)
Can't replicate. Is this still broken for you @SebastianTanoni?
