### ISSUE TITLE
User Appsettings not generating correctly

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#542]
The refactor in 5eb52dcd74866b55f31b1393784081e07ac40484 introduced a bug that causes the User Appsettings file to generate like this

```
{
  "TestingPlayerSlot": 0,
  "Warcraft3ExecutablePath": ""
}

```
instead of this
```
{
  "LaunchSettings": {
    "TestingPlayerSlot": 0,
    "Warcraft3ExecutablePath": ""
  }
}
```
resulting in an exception being thrown here
`var launchSettings = config.GetRequiredSection(nameof(LaunchSettings)).Get<LaunchSettings>();`

**Comment by YakaryBovine** [comment]
Ahh that explains so much, thank you!

**Comment by YakaryBovine** [comment]
Fixed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/7e4f3c9bb9496c75699ab407c9c460abc69bdf7c.
