### ISSUE TITLE
Illidan Hero dropping all items on death

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#559]

**Comment by YakaryBovine** [comment]
@SebastianTanoni What's the bug here? Don't all heroes drop items on death?

**Comment by YakaryBovine** [comment]
Nevermind, I see now - he shouldn't be dropping non-Artifacts.

**Comment by SavanticIO** [comment]
If I can get a bit more background on this I will take a look at it. Is this specificaly an issue for Illidan or is it likely to be for all heros? I think the issue is in RegisterItemSinkingPrevention not checking if the item is an artifact or not?

**Comment by YakaryBovine** [comment]
@SavanticIO I think you're completely correct. It's an issue for all heroes for sure.
In the C# version I changed the item sink code quite a lot. Previously it would detect hero deaths on water, then *recreate* all their items on shores. Now it instead marks all Artifacts as undroppable, and detects all hero deaths; when they're on land it drops their items, and when they're on water it drops their items on shores. I imagine that, indeed, we just need to make this behaviour only apply to Artifacts.
