### ISSUE TITLE
Black temple stays invulnerable

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#560]

**Comment by SavanticIO** [comment]
Other than the completion or failure of the Fel Horde 'Kil'sorrow Fortress' quest when should Black temple be made vulnerable?

**Comment by YakaryBovine** [comment]
@SavanticIO Yeah, seems like completing Kil'sorrow Fortress makes it vulnerable and that's fine. My only guess is that it should also be made vulnerable when that quest is *failed*, which isn't happening right now. But I'll mark it as awaiting response from @SebastianTanoni.

**Comment by SebastianTanoni** [comment]
Yup that looks correct, basically it should be vulnérable eventually?

**Comment by SavanticIO** [comment]
Yeah i see now that the OnFail isn't rescuing the Black Temple to nuetral aggressive

@YakaryBovine  I'll take this one
