### ISSUE TITLE
Gilneas has 2 tess greyman

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#563]

**Comment by SebastianTanoni** [comment]
When he entered scholomance, he got a lvl 1 tess with a summoned unit timer on it

**Comment by SebastianTanoni** [comment]
after she died he could ressurect her

**Comment by YakaryBovine** [comment]
Can't seem to replicate this one so I'll icebox it until we get a second report.
