### ISSUE TITLE
Forsaken northrend base did not unlock

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#564]

**Comment by SavanticIO** [comment]
Under what conditions should the base unlock for Forsaken or what quest is it tied to?

**Comment by YakaryBovine** [comment]
@SavanticIO I believe it's this quest from the latest vJASS version: https://github.com/AzerothWarsLR/AzerothWarsLR/blob/master/jass/Quests/Forsaken/QuestScholomanceBuild.j

**Comment by SavanticIO** [comment]
Okay yeah. I'll take this one
