### ISSUE TITLE
Infernal Juggernauts did not die

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#565]
![image](https://user-images.githubusercontent.com/47048283/204411461-f60218fa-1c07-43bc-a239-3330821b4e90.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/fbe2747b944676e40836709517ebfdb4122b8a99.
