### ISSUE TITLE
Tech orbs spawned in sentinel starting area?

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#566]
![image](https://user-images.githubusercontent.com/47048283/204411864-efb97757-5a81-40fa-b5d4-30f8acc08dbf.png)

Maybe item sincing is broken?

**Comment by SavanticIO** [comment]
Are the Tech Orbs supposed to spawn at all? I've found them in other parts of the map when testing.

If this is related to the item sinking prevention, I think the change I made in https://github.com/AzerothWarsLR/WarcraftLegacies/pull/582 would prevent this.

**Comment by SebastianTanoni** [comment]
@SavanticIO no, tech orbs are definately not that common and not supposed to spawn anywhere

**Comment by YakaryBovine** [comment]
@SebastianTanoni @SavanticIO Pretty sure the preplaced goblin heroes have these in their inventory, so indeed fixing the item sinking should have prevented this. I'll close it until we see it again.
