### ISSUE TITLE
1 2 3 4 5 6 7 8 9 debug appearing

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#570]

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/204412615-761dc6ed-d24c-4a98-9a18-3ba303555e56.png)

**Comment by SebastianTanoni** [comment]
![Uploading image.png…]()

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/204412713-6e327dde-cbd1-402a-9544-0e783db830d5.png)

it doubled

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/204412740-275266f2-f5a4-4ab9-aa31-3642b50f702a.png)

**Comment by SebastianTanoni** [comment]
I have a suspricion it is maiev ultimate

**Comment by SebastianTanoni** [comment]
ok, they are definately appearing with each of maiev attack, 1 timer for each time her ultimate procked

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/5e336a528c3cd2f81eea03dfbe1ab9281ec488b9.
