### ISSUE TITLE
leaver from the start of the game gold mines not removed

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#584]
![image](https://user-images.githubusercontent.com/47048283/204909400-8f3932b5-940f-4748-8633-81974019cd84.png)

**Comment by YakaryBovine** [comment]
@SebastianTanoni Where's this feature in the old version? Is it vJASS or GUI?

**Comment by SebastianTanoni** [comment]
It was gui

**Comment by YakaryBovine** [comment]
@SebastianTanoni I can't find it. Could you point me to the folder please?

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/205069619-cc288524-ebaf-4af5-9879-9821c5cec81b.png)

sorry my mistake, its the gold mine that needs removed

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/1484156c771be7d726ce630dee99ffaa63d2e59a.
