### ISSUE TITLE
Naxxramas quest completed and i didnt get it

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#589]
![image](https://user-images.githubusercontent.com/47048283/204911891-0de86fa9-f934-4276-bdb1-aa92e8b64f72.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/1921f0831f9444fbd95ae0c77b1b2bf098582847.
