### ISSUE TITLE
Should not register Artifacts which aren't in the game anymore

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#592]
![image](https://user-images.githubusercontent.com/8995690/204919356-c7489cf4-0d8f-4378-9729-56d1e742feec.png)
Also Thunderfury and Living Shadow.

**Comment by TracyTheBoy** [comment]
Demon Soul as well

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/e5bc27b46667b1c75b8b365d120ff219c06bd0cb.
