### ISSUE TITLE
Essence of Murmur name doesn't fit in the Artifact card

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#594]

**Comment by YakaryBovine** [comment]
@TracyTheBoy I think you reported this, right? What's your screen resolution? I don't get the issue on my end.

**Comment by TracyTheBoy** [comment]
> @TracyTheBoy I think you reported this, right? What's your screen resolution? I don't get the issue on my end.

WQHD -> 2560 x 1440

**Comment by YakaryBovine** [comment]
From research this is a resolution issue and I can't do anything about it.
