### ISSUE TITLE
Dalaran workers and elites should transform when taking the Nexus path

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#595]
![image](https://user-images.githubusercontent.com/8995690/204920194-d4edc7ea-1233-410c-9f6a-3f449eb46423.png)
![image](https://user-images.githubusercontent.com/8995690/204920010-a06f89d8-8c4e-4a0e-ac05-9ccf6c097be4.png)

**Comment by YakaryBovine** [comment]
Moving to 2.0 as Nexus is staying in 2.0.

**Comment by YakaryBovine** [comment]
@SebastianTanoni Was this how it worked in the vJASS version? I can't find anything on the subject.

**Comment by SebastianTanoni** [comment]
Nah, it didnt work like that

**Comment by YakaryBovine** [comment]
Excellent, then I'll leave that to you to either do or close.
