### ISSUE TITLE
Blacksmith caster reserach tooltips are confusing

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#596]
Each rank increases hp by 100 and armor by 2.
Rank 1 Tooltip reads **+100 hp** and +2 armor.
Rank 2 Tooltip reads **+200 hp**  and +2 armor.
Rank 3 Tooltip reads **+300 hp** and +2 armor.
So what it does is it states how much more hp your casters have if you add all the upgrades together.
The hp amount should stay the same for each rank.

This occured on the Gilneas faction but it looks like a general issue

**Comment by YakaryBovine** [comment]
I'm just going to mark this one as a bug since, indeed, the tooltip doesn't follow standards.
