### ISSUE TITLE
Warship tooltip is completely incorrect

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#599]
![image](https://user-images.githubusercontent.com/8995690/204949229-872c512d-cc1b-40c1-bd23-dcf5179c1a01.png)
Pretty sure this has never been the case for Warships and is just a leftover tooltip from when I started Kul'tiras and didn't finish it.

**Comment by HerrDave** [comment]
What is it supposed to say?

**Comment by YakaryBovine** [comment]
@HerrDave Just something similar to Battleship I guess. The wrong part is "Each Warship built is a different flagship with slightly different attributes." The ship doesn't do that.

**Comment by YakaryBovine** [comment]
@SebastianTanoni Who would own this ticket if not you? Didn't you implement Kul'tiras?

**Comment by SebastianTanoni** [comment]
I'm not sure I removed my assignment
