### ISSUE TITLE
Silvermoon still invulnearble after runestones died

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#603]

**Comment by SavanticIO** [comment]
The runestones are set as protectors of the Sunwell. Should they also be protectors of Silvermoon?

**Comment by YakaryBovine** [comment]
@SavanticIO I think you're exactly right. I probably added the Protector system after configuring Silvermoon. So I think we basically just need to remove the bottom line of this:

```cs
LegendSilvermoon = new Legend
      {
        Unit = preplacedUnitSystem.GetUnit(FourCC("h003")),
        DeathMessage = "The grand city of the high elves, Silvermoon, has been crushed by her enemies."
      };
      Legend.Register(LegendSilvermoon);
      LegendSilvermoon.Unit.SetInvulnerable(true);
```
And replace it with configuring some Protectors.

**Comment by SavanticIO** [comment]
@YakaryBovine If this is the case then I'll take this one
