### ISSUE TITLE
Frostwolf dropped, but no unit transfer or faction removal

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#605]

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/205104719-dc76eadd-6f1d-4203-a9dd-1c347f6acc74.png)

**Comment by YakaryBovine** [comment]
Might need a little help with this one please @SebastianTanoni. Mostly just for Savantic's question; did it display a message when the player left?

**Comment by SebastianTanoni** [comment]
Yes it did

**Comment by SebastianTanoni** [comment]
Just took the screenshot after it dissapeared

**Comment by YakaryBovine** [comment]
Can't reproduce this one so will icebox for now.

**Comment by SebastianTanoni** [comment]
This happened again, with scourge leaving! Multiboard did not update, cps were not transferred and units were not refunded

**Comment by SebastianTanoni** [comment]
But the player definately left, so there seem to be an issue with the leave method

**Comment by YakaryBovine** [comment]
I have added error checking to this function so it should tell us what's happening next time it comes up.
