### ISSUE TITLE
Thornspeaker training shows the wrong abilities

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#632]
![image](https://user-images.githubusercontent.com/8995690/205758327-0f6d8bfb-9515-4251-b830-da1394ebd11c.png)
![image](https://user-images.githubusercontent.com/8995690/205758341-8f0420bd-5221-460f-8f64-1769729e64cb.png)
![image](https://user-images.githubusercontent.com/8995690/205758346-4a073f95-3084-4324-8286-0f30640405e2.png)

**Comment by HerrDave** [comment]
Fixed both Tidesage and Thornspeaker's upgrade tooltips, both now correctly reference the proper spells
