### ISSUE TITLE
Create a few new quest for Draenei

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#638]
Make them work wherever Draenei starts

**Comment by TracyTheBoy** [comment]
Ideas for quests:

`1` Repairing the hull of the ship as a starter quest. Reward: Unlocking the area inside the ship
`2`  #637 as a mid to late game quest. Reward: Allows the ship to fly like Naxxramas
`3`  Going back to outland and reclaiming/rebuilding the draenai bases. This way the existing draenai outland stuff could be reused. Reward: Portal connecting outland and kalimdor.

**Comment by TracyTheBoy** [comment]
I am working on `1` atm.

**Comment by SebastianTanoni** [comment]
Rework odl quests for the 2 extra heroes
