### ISSUE TITLE
Frostwolf Quest refactor

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#643]
- [x] Draktharon book objective changed to controlling a few key locations in Kalimdor, spread around
- [x] Sea witch island removed, Frostwolf will start in Kalimdor next to the tauren caravan
- [x] Add a goldmine and remove the Kodo mechanic from Frostwolf. 
- [x] Thunderbuff quest just implies frostwolf fighting their way through the barrens up to Thunderbluff
- [x] Royal Plunder quest changed following the Diremaul removal, not sure yet what TO BE CHANGED

**Comment by TracyTheBoy** [comment]
@SebastianTanoni 
I would like to work in this but I am a little confused.
3 of the 5 tasks are marked as completed but the current code doesn't seem to reflect this.
Looking at the code that would be affected by this I don't see any recent changes.
Do you have these changes on a local branch and haven't commited them yet?

I just want to make sure that I don't start working on something that will cause conflicts later.

**Comment by SebastianTanoni** [comment]
> @SebastianTanoni I would like to work in this but I am a little confused. 3 of the 5 tasks are marked as completed but the current code doesn't seem to reflect this. Looking at the code that would be affected by this I don't see any recent changes. Do you have these changes on a local branch and haven't commited them yet?
> 
> I just want to make sure that I don't start working on something that will cause conflicts later.

Sorry, so the marked ones are things I dont want anymore. So I marked them as done.

Since we arent going for faction selection now, there is no need to detach the quests from fighting the night elves yet.

**Comment by SebastianTanoni** [comment]
The 2 tasks that are left are the only one required
