### ISSUE TITLE
Summon Garrison says it summons Footman but it actually summons Militia

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#695]
![image](https://user-images.githubusercontent.com/8995690/207759241-1e61e4bd-d465-4cf1-bc4a-5928b89fe93d.png)

**Comment by HerrDave** [comment]
Should the description be updated to specify it summons Militia, or should it be modified to summon Footmen?

**Comment by YakaryBovine** [comment]
@HerrDave The rule I use is: if in doubt, fix the tooltip.

**Comment by HerrDave** [comment]
Sounds good, I'll take care of it tomorrow

**Comment by HerrDave** [comment]
Fixed :)
(Tomorrow takes 10 days, it seems)
