### ISSUE TITLE
All Illidari building tooltips are incorrectly formatted

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#697]
Building tooltips should be formatted like this:
![image](https://user-images.githubusercontent.com/8995690/207760631-5d315c7f-254d-4387-905c-21b76c668b9f.png)

There should also be no punctuation in the Build tooltip. E.g. this:
![image](https://user-images.githubusercontent.com/8995690/207760715-618b816a-71d2-46e2-8f61-3322a8559275.png)
Should just be "Build Spawning Pit".

**Comment by HerrDave** [comment]
I'll take care of it :)

**Comment by YakaryBovine** [comment]
If you like! Don't burn out on tooltip stuff though.

**Comment by HerrDave** [comment]
Fixed
(Goodness me)
