### ISSUE TITLE
Stormwind Marshal Offensive Formation does not stack with Command Aura

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#699]
Offensive Formation re-uses the Command Aura buff so it incorrectly does not stack with Command Aura.
![image](https://user-images.githubusercontent.com/8995690/208204582-c7802c0b-a67f-49fd-bfb6-e2113221a0f4.png)

There are two options for fixing this:
1. Rename Offensive Formation to Command Aura, so that the ability and the buff matches. This would keep the current behaviour.
2. Create a new Offensive Formation buff and use that. This would mean the buff stacks.

**Comment by HerrDave** [comment]
Fixed
