### ISSUE TITLE
Configure the Control Point Defender system

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#709]
- [x] Configure GameSetup.cs as desired
- [x] Configure Defender appearances for every faction
- [x] Find a suitable icon for the Control Point's Fortify ability
- [x] Fix the pathing on the base Control Point Defender unit type
- [x] Configure Defender unit type IDs for every faction (example provided in LordaeronSetup.cs)

**Comment by SebastianTanoni** [comment]
Tower and cp dont grow in size with upgrade

**Comment by YakaryBovine** [comment]
@SebastianTanoni I've updated the system to use unique units for the towers instead of the skin system.
