### ISSUE TITLE
Add +1 armor to Control Points per Control Level

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#712]
![image](https://user-images.githubusercontent.com/47048283/208459423-58bfa8e3-5b70-4e75-bbdc-7aa823339ed1.png)

**Comment by SebastianTanoni** [comment]
(also they dont grow in size and their missile seems to all be arrows)

**Comment by YakaryBovine** [comment]
Sure.
