### ISSUE TITLE
Startnig the game as goblin, system error

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#734]
![image](https://user-images.githubusercontent.com/47048283/209252293-4bba2216-5d8b-4e37-b010-f09a0810e901.png)

**Comment by YakaryBovine** [comment]
This is less of a bug and more of a feature request so I've made a new ticket to reflect that: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/740

**Comment by YakaryBovine** [comment]
Fixed by removing Kezan Oil Supply's status as an oil user. It is now essentially useless though so might need some other function.
