### ISSUE TITLE
Goblin traders not spawning

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#737]
![image](https://user-images.githubusercontent.com/47048283/209252843-4e5bb947-e948-45f0-b4fe-3a26d631e8ec.png)

Trained about 5 just now, my income went up, but the unit didnt appear

**Comment by YakaryBovine** [comment]
![image](https://user-images.githubusercontent.com/8995690/209281658-5d2f20c6-2370-4e31-9cd6-1bc643fe831e.png)
Works for me in the latest version. Can you give me replication steps that are different from these:
1. Start the game as Goblin
2. Immediately type "-complete Business Expansion"
3. Train a Ship Trader and a Zeppelin Trader from the Kezan Trading Center
4. If the bug exists, the trained trader will disappear instantly
