### ISSUE TITLE
Legion Herald Unstable Transformation bugged

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#750]
![image](https://user-images.githubusercontent.com/93258020/209430126-be075fcd-35c7-4436-b84a-661a07395257.png)

**Comment by YakaryBovine** [comment]
@HerrDave Feel free to reassign this to me but if you do I'll likely do it in a different way.

**Comment by HerrDave** [comment]
@YakaryBovine I might've bitten off more than I could chew with this ability

If you can find a way to make it work, pizza's on me :)

Elsewise I might have to concede defeat to the Warcraft engine for now and remove the ability

**Comment by YakaryBovine** [comment]
@HerrDave Haha, all good, I'll take care of it. I'll keep your unit though I think.
