### ISSUE TITLE
Legion units pathing out of bounds

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#751]
![image](https://user-images.githubusercontent.com/93258020/209430272-466020ad-689d-46ad-8706-00961e5d1d7c.png)

**Comment by YakaryBovine** [comment]
@TracyTheBoy Could we re-open the bug report this was from and ask for more info? I'm not sure how this was done.

**Comment by TracyTheBoy** [comment]
Yea good idea. I have no idea either.

**Comment by SebastianTanoni** [comment]
easy, the remateralizition thing was set to a coordinate, which is now outside the map bound because we moved argus
