### ISSUE TITLE
Doomhammer spawing in the middle of nowhere

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#757]
![image](https://user-images.githubusercontent.com/93258020/209430572-485adbe0-e805-4b55-a4ca-d992616d690b.png)

**Comment by TracyTheBoy** [comment]
My ideas are that either:
- This is the location of the old Island where it used to lay on the ground
- It can not be spawned at the old location because there is water now and that's why it spawns smack in the middle of the map at (0,0)

**Comment by YakaryBovine** [comment]
@TracyTheBoy (1) is correct. Check out ArtifactSetup.cs I think.

**Comment by YakaryBovine** [comment]
Having this thing spawn on the ground is kinda silly anyway so I'll change how it works.

**Comment by SebastianTanoni** [comment]
best behavior should be: when thrall is first trained, he spawns with the hammer
