### ISSUE TITLE
Greymane towers don't change ownership if someone capture gate and are not invulnerable

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#761]
This is due to Gilneas quests still being setup. 
After turn 22 when the corresponding quests expire, they become neutral and vulnerable

**Comment by YakaryBovine** [comment]
@TracyTheBoy Great find, thankyou.

**Comment by SebastianTanoni** [comment]
But, since it has the objective selfExist, it should go hostile from the start no???

**Comment by TracyTheBoy** [comment]
ObjectiveSelfExists reacts to a factions Scorestatus changing. My guess is that when a faction is not in the game at all it doesn't change Scorestatus so the objective never fails

**Comment by SebastianTanoni** [comment]
That seems to be something we should change eventually then. Having a faction be absent should make their base hostile, not invulnerable

**Comment by TracyTheBoy** [comment]
I think there is also something else wrong with the changing owner mechanic of the towers. The towers don't change owner properly 
Could someone check this?
1. Destroy gate as any faction -> towers remain neutral but gate is now owned by the destroying player.
2. Destroy gate with a different faction -> gate is now owned by fhe new faction but towers are now owned by the previous faction

**Comment by SebastianTanoni** [comment]
It should be:

Whenever the gate is REPAIRED, the tower change owner, so a broken gate has neutral towers, a repaired gate has towers owned by whoever owns the gate

**Comment by YakaryBovine** [comment]
> That seems to be something we should change eventually then. Having a faction be absent should make their base hostile, not invulnerable

Seems reasonable. I'll make a bug ticket next time I'm at my computer for this.
