### ISSUE TITLE
exodar regail can jump to unintended locations

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#769]
Examples:: right corner of the map, inside naxx, inside ship and argus.

**Comment by YakaryBovine** [comment]
@SebastianTanoni I've assigned this to you since it's your content, but I realise that the solution will probably have to involve me coding something. Let me know what you need.

**Comment by SebastianTanoni** [comment]
hum, @YakaryBovine i need it so when the jump spell is cast, it checks if the cast location is in an illegal instance, and then cancels the spell.

Jump ability ID: A07D

**Comment by YakaryBovine** [comment]
@SebastianTanoni Sure. Options are:
1. You do it in GUI, specifying the blocked regions manually. Then I redo it in C# when I have time.
2. I give you some instructions on how to create a C# spell from our systems and interact with the InstanceManager. Not as hard as it sounds; Slipstream already does a very similar thing.

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210117796-fa139455-d221-4eec-aa0a-1e27e2c4c8a9.png)

done :)

**Comment by YakaryBovine** [comment]
Doesn't seem to work @SebastianTanoni. I can still teleport into any instance.

**Comment by SebastianTanoni** [comment]
reset exodar mana after test

**Comment by SebastianTanoni** [comment]
im throwing the towel, editor just refused to save,couldnt even test shit

**Comment by YakaryBovine** [comment]
We've determined that we'll replace the global link with Slipstream variations instead.
