### ISSUE TITLE
Slipstream can be used to make portals between instances 

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#771]
![image](https://user-images.githubusercontent.com/93258020/209437359-58a898a5-53d5-4425-b2e6-eecf11ddf20c.png)

**Comment by YakaryBovine** [comment]
@TracyTheBoy Funnily enough this spell actually handles instances correctly. The bug is really "Naxxramas is not registered as an instance in InstanceSetup.cs".

**Comment by TracyTheBoy** [comment]
In 6d59239a66fe0f67a23ff8917b28095f84370a29 Naxxramas got moved a bit so this specific case should be fixed.

Also I found this piece of code in `InstanceSetup.cs`
`    var naxxramas = new Instance("Naxxramas", Regions.NaxxramasInside);
      naxxramas.AddDependency(preplacedUnitSystem.GetUnit(Constants.UNIT_U01X_HEART_OF_NAXXRAMAS));
      naxxramas.AddDependency(preplacedUnitSystem.GetUnit(Constants.UNIT_E013_NAXXRAMAS_SCOURGE));
      InstanceSystem.Register(naxxramas);`

So it looks like there is a bug with the spell after all, what do you think @YakaryBovine ?

**Comment by YakaryBovine** [comment]
Yup, looks like it. Let's leave this issue open and I'll check it out.

**Comment by YakaryBovine** [comment]
@TracyTheBoy It turned out to indeed be an issue with Naxxramas configuration. The "NaxxramasInside" region doesn't actually cover the entire instance.
