### ISSUE TITLE
Former faction bases are neutral and invulnerable

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#772]
- [ ] #825
- [ ] Gilneas
- [ ] Stonemaul
- [ ] Maiev's base in Nagrand, Outland

**Comment by SebastianTanoni** [comment]
Maiev base should be hidden

**Comment by SebastianTanoni** [comment]
Gilneas should be a creep camp

**Comment by SebastianTanoni** [comment]
Stonemaul should be neutral hostile

**Comment by SebastianTanoni** [comment]
The other 3 will be fixed by #761

**Comment by YakaryBovine** [comment]
Split this into multiple tickets: #834, #835, #836
