### ISSUE TITLE
Center Suramar control point

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#776]
Minor thing but this hurts to look at.
![image](https://user-images.githubusercontent.com/93258020/209447239-d2694f74-ed74-4f62-93e1-a812fb6119e3.png)

**Comment by YakaryBovine** [comment]
@HerrDave Your call if you want to do this but I bet it bothers you too 😄.

**Comment by HerrDave** [comment]
It does @U@

It was centered in the World Editor, I wonder if a script changed the path from 3x3 to 2x2, that'd do it.

At any rate, Suramar is now a Sunken Ruins-style ruin now
