### ISSUE TITLE
Misplaced Doodad near Stratholme

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#777]
![image](https://user-images.githubusercontent.com/93258020/209447326-0fcd7088-5bcc-4e40-86f5-3aac180d746e.png)

**Comment by HerrDave** [comment]
This is intentional, it's a reference to the archway found in the same zone in World of Warcraft:

https://www.hiveworkshop.com/attachments/wowscrnshot_122522_211221-jpg.417411/

**Comment by TracyTheBoy** [comment]
Perfect
