### ISSUE TITLE
Golbin oil platform problems

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#786]
They spawn a little too close to the coast. In approximately 50% of cases it's impossible to build an oil rig because the neutral creeps from the coast will destroy it. 
Also oil rigs are logically supposed to be deep-sea things, so the proximity to the coast is weird.

**Comment by YakaryBovine** [comment]
Neither of these are bugs but it's valid feedback so I'll ponder it.

**Comment by YakaryBovine** [comment]
I increased the number of starting pools for Goblin from 1 to 4. This should drastically reduce the chances that the early pools are inaccessible.
