### ISSUE TITLE
Remove unused Gold Mines

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#787]
In the starting areas of:
- Illidari next to Silithus
- Militia in northern Tirisfal Glades
- Ahn Qiraj in southern Silithus
- Twilight in Twilight Highlands
- Dragonmaw in Twilight Highlands
- Gilneas in southern Silverpine Forest

And also in Nazjatar

**Comment by HerrDave** [comment]
Goldmines listed have been removed
