### ISSUE TITLE
Build is currently broken

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#800]
As per https://github.com/AzerothWarsLR/WarcraftLegacies/actions/runs/3801570708/jobs/6466173420 the code base doesn't compile. Needs to be fixed as a priority.

![image](https://user-images.githubusercontent.com/8995690/210025527-33b4ac2d-f2bf-4abe-a661-761c831f3f15.png)

**Comment by HerrDave** [comment]
Woah 0.0

Anything I can do; or shouldn't do?

**Comment by YakaryBovine** [comment]
@HerrDave I don't think so.

The main problem occurred because Constants were regenerated incorrectly. Constants need to be regenerated whenever any object is created, renamed, or deleted, or when any region is created, moved, renamed, or deleted. Regenerating Constants breaks all code references to the object. 

In https://github.com/AzerothWarsLR/WarcraftLegacies/actions/runs/3801570708/jobs/6466173420 Sebas regenerated Constants and fixed most of the resulting broken references, but he didn't fix them all. Whenever we regenerate Constants we should **always** make sure the map actually runs before committing the changes, because otherwise the problem just falls to the next person trying to test.

So this one is probably on Sebas to fix. In your case, it's probably not worth learning the level of C# needed to deal with it, and you should just rely on Sebas or I to regenerate Constants.

**Comment by YakaryBovine** [comment]
Sorry, just noticed I unassigned the wrong person.
