### ISSUE TITLE
QuestBusinessExpansion does not make Kezan invulnerable at game start

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#804]

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210378891-029fc4eb-03b4-4f96-993a-4dc7f1347f9a.png)

**Comment by YakaryBovine** [comment]
@SebastianTanoni The entire base needs to start invulnerable so that it can be rescued later, same as other base-acquisition quests.

![image](https://user-images.githubusercontent.com/8995690/210543919-710e22fa-1799-4083-912a-74c80f322357.png)

**Comment by YakaryBovine** [comment]
Closed by https://github.com/AzerothWarsLR/WarcraftLegacies/commit/f230271caf09b61d86f1d8c2d32ab7034a2fdbb5.
