### ISSUE TITLE
Do something with Ragnaros

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#806]
Currently he's just sitting in the top right corner. Probably some kind of shared quest to summon him to his house.

**Comment by SebastianTanoni** [comment]
il create the quest, make rag spawn, and add most ofthe conditions, il leave the rest to you

**Comment by SebastianTanoni** [comment]
Thrall's config
LegendNeutral.LegendRagnaros.ForceCreate()

**Comment by SebastianTanoni** [comment]
Need to make pedestal into the capturable config

**Comment by SebastianTanoni** [comment]
Spell ID: A0PY

**Comment by SebastianTanoni** [comment]
@YakaryBovine i finished everything ithink i could do for the rag thin!

**Comment by SebastianTanoni** [comment]
tell me if you think something is missing
