### ISSUE TITLE
Perfect defend doesn't reflect Piercing attacks, and may or may not reduce incoming damage

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#812]
No reflection for sure, idk about reduced dmg part
![image](https://user-images.githubusercontent.com/119281194/210206034-1347f6d5-df43-4d76-9749-c36bac117bc9.png)

**Comment by linaz2009** [comment]
Unless i am overthinking and it's not supposed to reflect arrows back like normal defend

**Comment by linaz2009** [comment]
https://imgur.com/a/SPF1kJa

**Comment by YakaryBovine** [comment]
No, you're definitely right and this is a bug. The tooltip indicates it should be reflecting some of those attacks. Thankyou for the .gif especially.

**Comment by SebastianTanoni** [comment]
Fixed it Pog

**Comment by SebastianTanoni** [comment]
elune grace is always wierd

**Comment by YakaryBovine** [comment]
Wow, you really did. Awesome
