### ISSUE TITLE
Animation freeze the Exodar Regalis prior to repairing it

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#813]
The Exodar Regalis currently floats around as if it's not on the ground even prior to being repaired.
It should start off with 0% animation speed and return to 100% once it's rebuilt.

I can do this if nobody else is interested.

**Comment by SebastianTanoni** [comment]
i could do it partly in GUI
im fine with changing it after the reward is given, but im bad at making things happen on initition in c#

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210378269-31b16e60-0be2-48e2-9119-8cec32a52b4f.png)
