### ISSUE TITLE
Fix the Demon Gate broken by the removal of QuestKilsorrowFortress

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#815]
QuestKilsorrowFortress was responsible for managing one of Fel Horde's Demon Gates, so that Gate now starts vulnerable and unhidden but can't be acquired. 
Relevant commit here: https://github.com/AzerothWarsLR/WarcraftLegacies/commit/ce3e131716099eea1c85bec2fce82d4b2a6e8984#diff-49afef5ac8965a7ff3203cb471d5cffd05996d6395bd3c9aab4efb20f94ce7ef

**Comment by SebastianTanoni** [comment]
il probably need some help here

**Comment by YakaryBovine** [comment]
@SebastianTanoni Sure. How do you want it to work?

**Comment by SebastianTanoni** [comment]
> @SebastianTanoni Sure. How do you want it to work? It's crossed my mind that we could just make Unfocused Demon Gates capturable and remove them from quest rewards.

I like it, lets do that!

**Comment by SebastianTanoni** [comment]
they are clunky as quest rewards
maybe just have 1 quest that requires to capture all ofthem to indicate to the player what to do

**Comment by SebastianTanoni** [comment]
or have all of them start unfocused and under the player control, and have a quest to upgrade them?

**Comment by SebastianTanoni** [comment]
Personally, i dont feel like doing much work on this, unless you want, il just make all gate start under Fel Horde control as unfocused and thats it
