### ISSUE TITLE
Kul'tiras tooltip issues V2

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#818]
- [x] Garrison says it has "Rising Tides", should be "Improved Crushing Wave"
- [x] Garrison says it trains "Snipers", actually trains "Navy Sniper"
- [x] Castle doesn't mention it researches "Full Scale Escalation"
- [x] Musketeer doesn't mention "Spell Resistance" ability
- [x] Animal Fury autocast icon doesn't match the buff icon (should be the same other than the autocast indicator)
- [ ] Scout Tower says it upgrades into Guard Tower or Cannon Tower but it actually upgrades into Guard Tower only
- [x] Guard Tower tooltip has a bunch of Arathor nonsense
- [x] Scout Tower tooltip doesn't mention Magic Sentry
- [x] Guard Tower tooltip says it can learn Magic Sentry, but it can't
- [x] Improved Guard Tower tooltip says it can learn Magic Sentry, but it can't
- [x] Thornspeaker Adept training mentions "their Human Form", but Thornspeakers do not change forms
- [x] Thornspeaker Master Training says it gives Thornspeakers Wickerbeast Form, but it does not; it actually unlocks the Wickerbeast unit

**Comment by YakaryBovine** [comment]
@SebastianTanoni You fixed everything perfectly but in doing so revealed some other issues, and there were also some I missed. Massive improvement already.
