### ISSUE TITLE
Tyrs Hand

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#825]

**Comment by SebastianTanoni** [comment]
https://user-images.githubusercontent.com/47048283/210375936-b8b0e3be-3eab-470c-858f-114436653304.png

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210380054-74f37596-291c-47ea-9ffb-b140c1f3fe1e.png)

**Comment by SebastianTanoni** [comment]
replace every building and unit to Lordaeron version @HerrDave

**Comment by HerrDave** [comment]
Done
