### ISSUE TITLE
Review Intro texts

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#826]
I wrote all the intro texts, but i suck at english, please make whatever i wrote better XD

**Comment by HerrDave** [comment]
The intro text is still done via trigger editor, right?

**Comment by SebastianTanoni** [comment]
yes

**Comment by SebastianTanoni** [comment]
all code is in vsstudio

**Comment by HerrDave** [comment]
What is a vsstudio

**Comment by TracyTheBoy** [comment]
> How would one go about updating the English on the intro text screens?
> 
> I don't seem to have anything called Vsstudio

Sebas is talking about the IDE Visual Studio, which most of us use to edit the code. But it is not required. You could use any text editor.
In the Source project under Setup -> FactionSetup you will find a file for each faction's setup (e.g Frostwolf, Dalaran etc.). Those files contain that text.

**Comment by HerrDave** [comment]
All factions except Forsaken, Scarlet and Zandalari updated
