### ISSUE TITLE
Change MOST Lordaeron building

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#827]
https://www.hiveworkshop.com/threads/lordaeron-buildings.341580/

**Comment by SebastianTanoni** [comment]
the buildings i DO NOT WANT changed are: The farms, and the altar

**Comment by SebastianTanoni** [comment]
CLARIFICATION

**Comment by SebastianTanoni** [comment]
Onlychange: main buildings, the marketplace, and the magic caster building

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210438485-f169b4a0-38f1-4744-a5d5-8b5c89457994.png)

actually, change the grpyhon avairy and workshop too, they look nice

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/210438534-71b25d5c-fa3a-46b9-9bfc-de685d90683b.png)

**Comment by HerrDave** [comment]
Done
