### ISSUE TITLE
Maiev's base in Outland starts neutral passive and vulnerable

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#836]

**Comment by YakaryBovine** [comment]
@SebastianTanoniIn theory the only thing you need to do is add the region to `src/WarcraftLegacies.Source/GameLogic/RemoveUnusedAreas.cs`

**Comment by SebastianTanoni** [comment]
well, i probably need to change the quest a bit too, the way to activate it was annoying

**Comment by SebastianTanoni** [comment]
how about a research at the vault of the wardens?

**Comment by SebastianTanoni** [comment]
just need to remvoe the spell
