### ISSUE TITLE
Gilneas

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#84]
Implement the entire Gilneas faction from the live vJASS version of the map, including:
* Any Quests
* Any spells
* Any mechanics

**Comment by YakaryBovine** [comment]
Hi @Sharkmike, I'm unassigning this for now since it's been a while and we need to get it started. Please reassign yourself if you find some time and pick it up!

**Comment by TracyTheBoy** [comment]
I could take a stab at this.
I don't know if I am capable of implementing everything by myself but I think I can do enough to contribute something of value.

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/202012025-ff7aba31-0ac8-4713-86d6-805cc362a897.png)

circle is castle, X is doodad (so not player controlled)
