### ISSUE TITLE
Review new ship tooltips

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#851]

**Comment by YakaryBovine** [comment]
@SebastianTanoni I'm guessing the ship stuff isn't totally done yet so I'll save this to the end.

**Comment by YakaryBovine** [comment]
@SebastianTanoni I'm guessing the ship stuff isn't totally done yet so I'll save this to the end.

**Comment by SebastianTanoni** [comment]
@YakaryBovine ship stuff is done on my end

**Comment by SebastianTanoni** [comment]
Only thing missing is some models

**Comment by YakaryBovine** [comment]
Honestly the tooltips are pretty good. Follow-up ticket here: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/883
