### ISSUE TITLE
Kul'tiras quests

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#87]
Implement all Kul'tiras quests from the live vJASS version.
Many of these have been started, but none of them have been tested. They will likely need changes.

**Comment by TracyTheBoy** [comment]
Hi, I am working on these quests right now and would like to test my changes but I am having issues starting the map as Kul'Tiras.
The game crashes during the loading screen when I set my TestingPlayerSlot in the appsettings to 21 which is Kul'Tiras as far as I can tell.
I tested it with other player numbers I used previously and those are still working so it must be an issue specific to that faction

**Comment by YakaryBovine** [comment]
Sweet, I'll check in a bit when I can get a break from work. My guess would be that Kul'tiras is currently set to the wrong player slot entirely in-game and the one I'm using is actually unused. But we'll see!

**Comment by TracyTheBoy** [comment]
Hi, that was indeed it. I compared the player slots in the game with the configurations in the code and they indeed didn't fit.
I matched them and now it's working.
Thanks

**Comment by YakaryBovine** [comment]
Ah, brilliant!

**Comment by TracyTheBoy** [comment]
So I got this mostly working but I am facing some issues I don't know how to solve on that last quest `QuestUnlockShip`.
When the quest is failed your heroes are supposed to spawn inside the ship but I can't get them to teleport to the correct location.
When i use the same location `ShipAmbient` as in the Jass version, the heroes spawn in a completely different location.
Same thing with the ship. It's supposed to spawn at the coast of Southshore but it spawns too far to the right even though I am using the same location as in the Jass Verison.
The coordinates in the `Regions` class probably don't match the actual locations in the map but not sure.
Anyways I'm kinda lost on how to deal with this properly

**Comment by YakaryBovine** [comment]
Sweet, I'll look into it tomorrow my time. Sounds like some region stupidity I'll have to solve in the map file; your code is probably fine.

**Comment by YakaryBovine** [comment]
Ok - the ShipAmbient region was in a really odd place so I moved it. Not sure if it was the correct move but we'll find out. I didn't move SouthshoreUnlock; it's needed for another quest, and I think yours should work anyway since you're not spawning the ship, only issuing an order to it.

Unfortunately the Regions.cs file is generated from the actual in-map Regions list: 
![image](https://user-images.githubusercontent.com/8995690/200701895-bcb7e638-460c-4286-8fe5-739f874cfea6.png)
So you would need to edit the actual .w3x file to change them.
