### ISSUE TITLE
A way to get non-intended hero into another path

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#880]
![image](https://user-images.githubusercontent.com/119281194/210666976-7f3dabd4-c2e1-4f79-a9a2-b099791eff36.png)
![image](https://user-images.githubusercontent.com/119281194/210666996-bf885f75-e335-4bcc-9732-2623efaf443e.png)

**Comment by linaz2009** [comment]
queue while completing nexus quest

**Comment by SebastianTanoni** [comment]
Wierd, when he is trained, since you shouldnt have medivh in your config, he should dissapear

**Comment by SebastianTanoni** [comment]
AH GOT IT ty

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/211347518-f7271921-e3a5-4e03-9f40-578aa860b5d5.png)
Wasn't fixed (2.01 version)

**Comment by linaz2009** [comment]
same goes for Antonidas

**Comment by SebastianTanoni** [comment]
@YakaryBovine I dont know how to fix this. It shouldnt be an issue since the path no longer removes heroes

**Comment by YakaryBovine** [comment]
Cool, sounds like it's not an issue then.
