### ISSUE TITLE
Ship tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#883]
- [x] Most (or possibly all) Blacksmiths do not mention Improved Cannons or Fortified Hulls in their extended tooltips
- [x] Boarding Vessel does not mention its ability to Load units in its extended tooltip
- [x] Bombard tooltip suggests that it is "Strong versus buildings, Weak versus ships" but neither of these things are true as it cannot attack either of them at all
- [x] Incendiary Arrows tooltip does not indicate how much extra damage it does

**Comment by SebastianTanoni** [comment]
Boarding vessels cant load units anymore, there are transport ships

**Comment by YakaryBovine** [comment]
@SebastianTanoni Boarding vessels can load units in the current version of the map. Maybe some changes you meant to push that got corrupted before you could?

**Comment by HerrDave** [comment]
All blacksmiths (except Illidari) now have unified upgrade names (Forged Weaponry, Armor Plating) and mention all available upgrades, specific to each faction.
