### ISSUE TITLE
Guardian of Tirisfal quest cannot be completed without destroying Dalaran

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#887]
Book of medivh require dalaran's capital destruction, while Guardian of Tirisfal requires book to be completed.
![image](https://user-images.githubusercontent.com/8995690/210740754-b8a0ad7c-5181-448a-ba15-c980d7fcf427.png)
![image](https://user-images.githubusercontent.com/8995690/210740788-e72ec95c-8552-4f2b-b325-8a9c2e0c356b.png)

**Comment by TracyTheBoy** [comment]
Could we make it so that Dalaran Heroes only need to meet the level requirements?

**Comment by YakaryBovine** [comment]
@TracyTheBoy Yep, that would seem to make sense.

**Comment by SebastianTanoni** [comment]
I'm surprised it's not this already
