### ISSUE TITLE
Alexandros spellbook abuse

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#895]
![image](https://user-images.githubusercontent.com/119281194/210787868-b40dd87e-838d-40c2-8314-944648236ef5.png)
![image](https://user-images.githubusercontent.com/119281194/210788021-78725c49-2411-4432-9296-ef1cedce53de.png)

**Comment by linaz2009** [comment]
Alexandros keep his spellbook full of passives after using tome of retraining

**Comment by linaz2009** [comment]
And he return all skillpoints

**Comment by YakaryBovine** [comment]
Merged into https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1026
