### ISSUE TITLE
Quel'thalas blood elves quest is sus

### ISSUE THREAD

**Issue by linaz2009** [AzerothWarsLR/WarcraftLegacies#897]
https://imgur.com/a/pot8x0O

**Comment by linaz2009** [comment]
maybe it's SP cheat issue

**Comment by linaz2009** [comment]
kicking legion with -kick 23 didn't make Nexus vulnerable, so had to use cheat

**Comment by YakaryBovine** [comment]
Fixed, cheers. (Accidentally looked at my phone and saw this and had to fix it... bed for real now)
