### ISSUE TITLE
Sanctum and champion hall are invulnerable

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#915]

**Comment by SebastianTanoni** [comment]
not even sure if this is a bug

**Comment by YakaryBovine** [comment]
@SebastianTanoni Not a bug. The Construction Sites are invulnerable, and are destroyed automatically when Stormwind Keep is destroyed. That's how it was meant to work in the JASS version according to the triggers, but it was bugged so I fixed it.
