### ISSUE TITLE
Shaladrassil's Blessing spawns far too many Treants when taking incidental damage

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#927]
Shaladrassil's Blessing spawns Treants when it gets damaged from max HP, but the CPs also have regeneration. So if the CP is continously damaged then allowed to regenerate, you get way too many Treants.

**Comment by YakaryBovine** [comment]
Control Points no longer regenerate hit points so this shouldn't be an issue anymore.
