### ISSUE TITLE
Stormwind GUI triggers

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#93]
- [ ] Stormwind
- [ ] Dark Green Caster Building Construction
- [ ] Dark Green Melee Building Construction

See discussion below. This system is being simplified so that it uses normal building upgrades instead of a complex research system involving doodads.

**Comment by YakaryBovine** [comment]
@SebastianTanoni I think I saw you mention something about changing how the Stormwind special tech buildings work. Can you give any info about that or should I just recreate them as is?

**Comment by SebastianTanoni** [comment]
Basically they are just normal buildings now
there is no longer any doodads appearing or dissapearing

**Comment by SebastianTanoni** [comment]
So you upgrade the building and thats it

**Comment by SebastianTanoni** [comment]
![image](https://user-images.githubusercontent.com/47048283/193276431-a187a3d1-c517-4280-96d4-4c8ddf2ef683.png)


![image](https://user-images.githubusercontent.com/47048283/193276504-64aa54a2-8c96-416e-b3b7-da5e34e329b6.png)

These are the only things the codes needs to do, im sure this can be added to the quest? Maybe if theres a quest to build both buildings

**Comment by YakaryBovine** [comment]
Excellent thanks, that's much easier.
