### ISSUE TITLE
The "Argus Incursion" quest doesn't provide enough information

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#934]
- [x] CompletionPopup is just a copy and paste of RewardDescription; should be a flavour-only message
- [x] Says that it lets you research Astral Walk, but it doesn't indicate from where as quests normally do
- [x] Says that it lets you "build a shop" but doesn't actually name the shop as quests normally do
- [x] Grants control of two Legion Nexus buildings, but doesn't indicate that anywhere in the RewardDescription

**Comment by linaz2009** [comment]
Legion actually have control over nexuses before completing quest

**Comment by YakaryBovine** [comment]
@linaz2009 Interesting... Not sure what's intended here. The Nexus in Northrend is neutral passive at game start but the one in Alterac Valley is not. @SebastianTanoni how is the ownership meant to work here?

**Comment by SebastianTanoni** [comment]
Both should be always available at All timr
