### ISSUE TITLE
Illidari tooltip issues

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#936]
- [ ] All unit tooltips are incorrectly formatted except Scylla and Naga Sea Witch
- [x] Naga Sea Witch tooltip doesn't mention Resistant Skin or Spell Resistance
- [x] Neither Naga Siren nor Mur'gul Shadowcaster have caster upgrade icons
- [x] The Lost Ones quest says it allows construction of the Draenei Hut, but no such building exists
- [x] Vindication is autocast but doesn't have an autocast icon
- [x] Ashtongue Mystic has the Amphibious ability but is not amphibious
- [x] Lady Vashj tooltip doesn't mention Amphibious
- [x] Akama's Feral Spirit refers to Thrall
- [x] Akama's Shadow Strike shares a name and effect with normal Shadow Strike, but has a different icon. The buff's icon is also completely different
- [x] Shadow Aura buff is named Fear Aura, doesn't have a matching icon, and is green-named rather than red
- [x] The Eye of Sargeras quest shares an icon with the Tomb of Sargeras quest
- [x] The Eye of Sargeras quest says it gives you the Eye of Sargeras, but it doesn't
- [x] Najentus' tooltip doesn't mention Amphibious
- [x] Najentus' Summon Mur'gul learn tooltip is improperly formatted
- [x] Najentus' Summon Mur'gul says it summons "Naga Mur'gul", but it summons Mur'gul Tidewarriors
- [x] Illidan's Demon Rage buff is named Berserk, and doesn't have a matching icon
- [x] Illidan's Demonic Shield buff is Divine Shield
- [x] Illidan's Demonic Rage says it lasts 7 seconds, but it lasts 3
- [x] Illidan's Metamorphosis tooltip doesn't mention damage bonus, and mentions an incorrect hit point bonus
- [x] "Portal to Black Temple" says it has a range of 3000, but it is much lower

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/212499750-b813a603-28b6-4108-ba94-88e71e46e6ad.png)
Meta doesn't mention dmg boost

**Comment by Technopig1992** [comment]
updated tooltips for all illidari units to standard format .
