### ISSUE TITLE
Implement relevant dialogue from all Warcraft 3 campaign missions

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#945]
**Human: Reign of Chaos**

- [x] Human01
- [x] Human02
- [x] Human02Interlude
- [x] Human03
- [x] Human04
- [x] Human05
- [x] Human05Interlude
- [x] Human06
- [x] Human06Interlude
- [x] Human07
- [x] Human08
- [x] Human09

**Undead: Reign of Chaos**
- [x] Undead01
- [x] Undead02
- [x] Undead02Interlude
- [x] Undead03A
- [x] Undead03B
- [x] Undead04A
- [x] Undead04B
- [x] Undead05A
- [x] Undaad05BInterlude
- [x] Undead06
- [x] Undead07
- [x] Undead08

**Orcs: Reign of Chaos**

- [x] O01
- [x] O02
- [x] O03
- [x] O04
- [x] O05
- [x] O06
- [x] O07
- [x] O08

**Night Elves: Reign of Chaos**

- [x] N01
- [x] N02
- [x] N03
- [x] N04
- [x] N05
- [x] N06
- [x] N06Interlude
- [x] N07

**Sentinels: Frozen Throne**

- [x] S01
- [x] S02
- [x] S03
- [x] S04
- [x] S05
- [x] S06
- [x] S07
- [x] S08

**Blood Elves: Frozen Throne**

- [x] Human01x
- [x] Human02x
- [x] Human02xInterlude
- [x] Human03x
- [x] Human04x
- [x] Human04xInterlude
- [x] Human05x
- [x] Human05xInterlude
- [x] Human06x
- [x] Human07x
- [x] Human07xInterlude

**Undead: Frozen Throne**
- [x] Undead01x
- [x] Undead01xInterlude
- [x] Undead02x
- [x] Undead02xInterlude
- [x] Undead03x
- [x] Undead04x
- [x] Undead05x
- [x] Undead06x
- [x] Undead07Ax
- [x] Undead07Bx
- [x] Undead07Cx
- [x] Undead07CxInterlude
- [x] Undead08x

**Rexxar: The Frozen Throne**
- [x] To Tame a Land
- [x] Old Hatreds
- [x] A Blaze of Glory

**Comment by linaz2009** [comment]
![image](https://user-images.githubusercontent.com/119281194/211172653-3b1fe6fd-9578-4d90-bf50-551caf001e10.png)
what about this one

**Comment by linaz2009** [comment]
Arthas: You waste your breath, Mal'Ganis.  I heed only the voice of Frostmourne
now.

Mal'Ganis: You hear the voice of the Dark Lord.  He whispers to you through the
blade you wield.  What does he say, young human?  What dose the Dark Lord of
the Dead tell you now?

Arthas: He tells me that the time for my vengeance has come.
from human Chapter Seven: The Shores of Northrend
