### ISSUE TITLE
Problems when canceling a gate repair

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#972]
When the gate is destroyed and you cancel the repair, this happens
![image](https://user-images.githubusercontent.com/93258020/211208680-a19e56fc-8635-4e09-a8f4-800c585c59e2.png)

**Comment by YakaryBovine** [comment]
@TracyTheBoy The bug here is that the gate looks like it's in-tact despite not being repaired, right?

**Comment by TracyTheBoy** [comment]
Yes that is the bug. You can still path through it so it is just a visual issue
