### ISSUE TITLE
Units spawned by the plague remain under Scourge control even when scourge leaves the game

### ISSUE THREAD

**Issue by TracyTheBoy** [AzerothWarsLR/WarcraftLegacies#973]
![image](https://user-images.githubusercontent.com/93258020/211208783-1e8e0d99-e493-44e6-8b86-581fcca3bf2c.png)

**Comment by TracyTheBoy** [comment]
I have thought about it more and what this bug could actually be is:  Units spawned by the plague (by destroying an infected building for example) after scourge left the game remain under Scourge control.

**Comment by YakaryBovine** [comment]
@TracyTheBoy Yeah that'll be exactly it. Probably just need to modify the Plague power a little bit.
